#include <bits/stdc++.h>
using namespace std;
signed main() {
    cout<<"ABCDEFGHIJKLMNOPQR\nBABCDEFGHIJKLMNOPQ\nCBABCDEFGHIJKLMNOP\nDCBABCDEFGHIJKLMNO\nEDCBABCDEFGHIJKLMN\nFEDCBABCDEFGHIJKLM\nGFEDCBABCDEFGHIJKL\nHGFEDCBABCDEFGHIJK\nIHGFEDCBABCDEFGHIJ\nJIHGFEDCBABCDEFGHI";
    return 0;
}