from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=3005,M=10005;int h[N],to[M],nx[M],q[N],c[N];double w[M],d[N];bool z[N];int n,m;bool C(double x){fill(d+1,d+n+1,0);fill(c+1,c+n+1,0);fill(z+1,z+n+1,1);int l=0,r=n;for(int i=0;i<n;i++)q[i]=i+1;while(l<r){int u=q[l++%N];z[u]=0;for(int i=h[u];i;i=nx[i])if(d[to[i]]>d[u]+w[i]-x+1e-12){d[to[i]]=d[u]+w[i]-x;c[to[i]]=c[u]+1;if(c[to[i]]>=n)return 1;if(!z[to[i]])z[to[i]]=1,q[r++%N]=to[i];}}return 0;}int main(){ios::sync_with_stdio(0);cin.tie(0);cin>>n>>m;for(int i=1,u;i<=m;i++)cin>>u>>to[i]>>w[i],nx[i]=h[u],h[u]=i;double l=-1e7,r=1e7;for(int i=0;i<70;i++){double x=(l+r)/2;if(C(x))r=x;else l=x;}cout<<fixed<<setprecision(8)<<r<<'\n';}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=12;double w[N][N],r=1e100;bool v[N];int n;void D(int s,int x,int k,double z){v[x]=1;for(int y=1;y<=n;y++)if(w[x][y]<1e90){if(y==s)r=min(r,(z+w[x][y])/(k+1));else if(!v[y])D(s,y,k+1,z+w[x][y]);}v[x]=0;}int main(){ios::sync_with_stdio(0);cin.tie(0);int m;cin>>n>>m;for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)w[i][j]=1e100;while(m--){int x,y;double z;cin>>x>>y>>z;w[x][y]=min(w[x][y],z);}for(int i=1;i<=n;i++)D(i,i,0,0);cout<<fixed<<setprecision(8)<<r<<'\n';}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int n=g()%min(3000ULL,max(2ULL,z))+2,m=n+g()%max(1,n);cout<<n<<' '<<m<<'\n';for(int i=1;i<=n;i++)cout<<i<<' '<<i%n+1<<' '<<(int)(g()%20001)-10000<<'\n';for(int i=n;i<m;i++){int x=g()%n+1,y=(x-1+g()%(n-1)+1)%n+1;cout<<x<<' '<<y<<' '<<(int)(g()%20001)-10000<<'\n';}}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const int N=10,M=40;int a[M],b[M],q[N],c[N];double w[M],d[N],e[N][N],r;bool z[N],v[N];int n,m;bool C(double x){fill(d,d+n,0);fill(c,c+n,0);fill(z,z+n,1);int l=0,R=n;for(int i=0;i<n;i++)q[i]=i;while(l<R){int u=q[l++%N];z[u]=0;for(int i=0;i<m;i++)if(a[i]==u&&d[b[i]]>d[u]+w[i]-x+1e-11){d[b[i]]=d[u]+w[i]-x;c[b[i]]=c[u]+1;if(c[b[i]]>=n)return 1;if(!z[b[i]])z[b[i]]=1,q[R++%N]=b[i];}}return 0;}void D(int s,int x,int k,double y){v[x]=1;for(int i=0;i<n;i++)if(e[x][i]<1e90){if(i==s)r=min(r,(y+e[x][i])/(k+1));else if(!v[i])D(s,i,k+1,y+e[x][i]);}v[x]=0;}int main(int Cc,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=Cc>1?stoi(V[1]):1000;unsigned long long S=Cc>2?stoull(V[2]):1;mt19937_64 g(S);while(R--){n=g()%7+2;m=n+g()%10;for(int i=0;i<n;i++)for(int j=0;j<n;j++)e[i][j]=1e100;for(int i=0;i<m;i++){a[i]=i<n?i:g()%n;b[i]=i<n?(i+1)%n:g()%n;w[i]=(int)(g()%41)-20;e[a[i]][b[i]]=min(e[a[i]][b[i]],w[i]);}double l=-30,h=30;for(int i=0;i<65;i++){double x=(l+h)/2;if(C(x))h=x;else l=x;}r=1e100;for(int i=0;i<n;i++)D(i,i,0,0);if(abs(h-r)>1e-7)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P3199','P3199 [HNOI2009] 最小圈',r'二分平均值 $x$，把每条边权改成 $w-x$。图中存在平均值小于 $x$ 的圈，当且仅当新图存在负环；每次用从所有点同时出发的 SPFA 判负环。二分足够次数即可达到八位小数精度。',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},extra=[('2 2\n1 2 1\n2 1 3\n','2.00000000\n'),('3 3\n1 2 -1\n2 3 2\n3 1 2\n','1.00000000\n')])

B=r'''#include <bits/stdc++.h>
using namespace std;const int N=5005,M=6005;int h[N],to[M],nx[M],q[N],c[N];double w[M],d[N];bool z[N];int n,m,e;void A(int x,int y,int v){to[++e]=y;w[e]=v;nx[e]=h[x];h[x]=e;}bool C(double x){fill(d+1,d+n+1,0);fill(c+1,c+n+1,0);fill(z+1,z+n+1,1);int l=0,r=n;for(int i=0;i<n;i++)q[i]=i+1;while(l<r){int u=q[l++%N];z[u]=0;for(int i=h[u];i;i=nx[i])if(d[to[i]]>d[u]+w[i]-x+1e-12){d[to[i]]=d[u]+w[i]-x;c[to[i]]=c[u]+1;if(c[to[i]]>=n)return 1;if(!z[to[i]])z[to[i]]=1,q[r++%N]=to[i];}}return 0;}int main(){ios::sync_with_stdio(0);cin.tie(0);cin>>n>>m;n+=2;while(m--){int u,v,a,b,c,d;cin>>u>>v>>a>>b>>c>>d;if(u==n-1||v==n-1)continue;A(u,v,b+d);if(c)A(v,u,a-d);}double l=-2000,r=2000;for(int i=0;i<70;i++){double x=(l+r)/2;if(C(x))r=x;else l=x;}cout<<fixed<<setprecision(2)<<-r<<'\n';}
'''
BB=r'''#include <bits/stdc++.h>
using namespace std;const int N=12;double w[N][N],r=1e100;bool z[N];int n;void D(int s,int x,int k,double v){z[x]=1;for(int y=1;y<=n;y++)if(w[x][y]<1e90){if(y==s)r=min(r,(v+w[x][y])/(k+1));else if(!z[y])D(s,y,k+1,v+w[x][y]);}z[x]=0;}int main(){ios::sync_with_stdio(0);cin.tie(0);int m;cin>>n>>m;n+=2;for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)w[i][j]=1e100;while(m--){int u,v,a,b,c,d;cin>>u>>v>>a>>b>>c>>d;if(u==n-1||v==n-1)continue;w[u][v]=min(w[u][v],(double)b+d);if(c)w[v][u]=min(w[v][u],(double)a-d);}for(int i=1;i<=n;i++)D(i,i,0,0);cout<<fixed<<setprecision(2)<<-r<<'\n';}
'''
BG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):10;mt19937_64 g(s);int n=g()%min(100ULL,max(2ULL,z))+2,m=n+1+g()%n,C=g()%20+1;cout<<n<<' '<<m<<'\n';cout<<n+1<<" 1 0 0 "<<C<<" 0\n";for(int i=1;i<=n;i++)cout<<i<<' '<<(i==n?n+2:i+1)<<' '<<g()%11<<' '<<g()%11<<' '<<C<<' '<<g()%21<<'\n';for(int i=n+1;i<m;i++){int x=g()%n+1,y=x==n?n+2:x+1+g()%(n-x+1);if(y==n+1)y=n+2;cout<<x<<' '<<y<<' '<<g()%11<<' '<<g()%11<<" 0 "<<g()%21<<'\n';}}
'''
BS=r'''#include <bits/stdc++.h>
using namespace std;const int N=12,M=50;int a[M],b[M],q[N],c[N];double w[M],d[N],W[N][N],r;bool z[N],v[N];int n,e;bool C(double x){fill(d,d+n,0);fill(c,c+n,0);fill(z,z+n,1);int l=0,R=n;for(int i=0;i<n;i++)q[i]=i;while(l<R){int u=q[l++%N];z[u]=0;for(int i=0;i<e;i++)if(a[i]==u&&d[b[i]]>d[u]+w[i]-x+1e-11){d[b[i]]=d[u]+w[i]-x;c[b[i]]=c[u]+1;if(c[b[i]]>=n)return 1;if(!z[b[i]])z[b[i]]=1,q[R++%N]=b[i];}}return 0;}void D(int s,int x,int k,double y){v[x]=1;for(int i=0;i<n;i++)if(W[x][i]<1e90){if(i==s)r=min(r,(y+W[x][i])/(k+1));else if(!v[i])D(s,i,k+1,y+W[x][i]);}v[x]=0;}int main(int Cc,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=Cc>1?stoi(V[1]):1000;unsigned long long S=Cc>2?stoull(V[2]):1;mt19937_64 g(S);while(R--){n=g()%6+2;e=0;for(int i=0;i<n;i++)for(int j=0;j<n;j++)W[i][j]=1e100;for(int i=0;i<n;i++){int A=g()%11,B=g()%11,F=g()%21;a[e]=i;b[e]=i+1==n?0:i+1;w[e]=B+F;W[a[e]][b[e]]=min(W[a[e]][b[e]],w[e]);e++;a[e]=i+1==n?0:i+1;b[e]=i;w[e]=A-F;W[a[e]][b[e]]=min(W[a[e]][b[e]],w[e]);e++;}double l=-30,h=30;for(int i=0;i<65;i++){double x=(l+h)/2;if(C(x))h=x;else l=x;}r=1e100;for(int i=0;i<n;i++)D(i,i,0,0);if(abs(h-r)>1e-7)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P3288','P3288 [SCOI2014] 方伯伯运椰子',r'把一次扩容看作原方向残量边，代价为 $b_i+d_i$；容量正的道路还可压缩，对应反向残量边，代价为 $a_i-d_i$。合法调整分解成残量图中的环，调整收益除以次数就是环平均代价的相反数，因此答案是残量图最小平均环的相反数。入口边不加入残量图。',{'.cpp':B,' 数据生成.cpp':BG,' 暴力.cpp':BB,' 对拍.cpp':BS},extra=[('2 4\n3 1 0 0 1 0\n1 4 0 0 1 10\n1 2 0 0 0 1\n2 4 0 0 0 1\n','2.67\n'),('2 4\n3 1 0 0 2 0\n1 4 0 0 2 9\n1 2 1 0 0 1\n2 4 1 0 0 1\n','2.33\n'),('2 4\n3 1 0 0 1 0\n1 4 0 0 1 12\n1 2 0 0 0 0\n2 4 0 0 0 0\n','4.00\n')])
