from build_lib import add,q,w

def statement(p,b,d,i,o,h):
 x=q(p);z=x['contenu'];g=lambda y,k:y.get(k,'').strip()
 s=f"# {p} {z['name']}\n\n## 中文题面\n\n### 题目描述\n\n{g(z,'description')}\n\n### 输入格式\n\n{g(z,'formatI')}\n\n### 输出格式\n\n{g(z,'formatO')}"
 for k,a in enumerate(x.get('samples',[]),1):s+=f"\n\n### 样例 {k}\n\n```text\n{a[0].rstrip()}\n```\n\n```text\n{a[1].rstrip()}\n```"
 s+=f"\n\n### 说明与限制\n\n{g(z,'hint')}\n\n## English Statement\n\n### Description\n\n{d}\n\n### Input\n\n{i}\n\n### Output\n\n{o}\n\n### Constraints\n\n{h}"
 w(b+'.md',s)

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=262144,P=998244353,G=3;int a[N],b[N],x[N],y[N],r[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,t=1;j<l/2;j++,t=1LL*t*w%P){int u=a[i+j],v=1LL*t*a[i+j+l/2]%P;a[i+j]=(u+v)%P;a[i+j+l/2]=(u-v+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void s(int l,int h){if(l==h)return;int m=(l+h)>>1;s(l,m);int n=1,k=0;while(n<(m-l+1)+(h-l+1)-1)n<<=1;while((1<<k)<n)k++;for(int i=0;i<n;i++)x[i]=i<=m-l?a[l+i]:0,y[i]=i&&i<=h-l?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(k-1));f(x,n,1);f(y,n,1);for(int i=0;i<n;i++)x[i]=1LL*x[i]*y[i]%P;f(x,n,-1);for(int i=m+1;i<=h;i++)a[i]=(a[i]+x[i-l])%P;s(m+1,h);}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=1;i<n;i++)cin>>b[i];a[0]=1;s(0,n-1);for(int i=0;i<n;i++)cout<<a[i]<<' ';cout<<'\n';}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005,P=998244353;int a[N],b[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=1;i<n;i++)cin>>b[i];a[0]=1;for(int i=1;i<n;i++)for(int j=1;j<=i;j++)a[i]=(a[i]+1LL*a[i-j]*b[j])%P;for(int i=0;i<n;i++)cout<<a[i]<<' ';cout<<'\n';}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;mt19937_64 g(s);z=min(100000ULL,max(2ULL,z));int n=g()%(z-1)+2;cout<<n<<'\n';for(int i=1;i<n;i++)cout<<g()%998244353<<' ';cout<<'\n';}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const int N=256,P=998244353,G=3;int a[N],b[N],x[N],y[N],r[N],o[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,t=1;j<l/2;j++,t=1LL*t*w%P){int u=a[i+j],v=1LL*t*a[i+j+l/2]%P;a[i+j]=(u+v)%P;a[i+j+l/2]=(u-v+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void s(int l,int h){if(l==h)return;int m=(l+h)>>1;s(l,m);int n=1,k=0;while(n<(m-l+1)+(h-l+1)-1)n<<=1;while((1<<k)<n)k++;for(int i=0;i<n;i++)x[i]=i<=m-l?a[l+i]:0,y[i]=i&&i<=h-l?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(k-1));f(x,n,1);f(y,n,1);for(int i=0;i<n;i++)x[i]=1LL*x[i]*y[i]%P;f(x,n,-1);for(int i=m+1;i<=h;i++)a[i]=(a[i]+x[i-l])%P;s(m+1,h);}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long z=C>2?stoull(v[2]):1;mt19937_64 g(z);while(R--){int n=g()%60+2;memset(a,0,sizeof a);memset(b,0,sizeof b);memset(o,0,sizeof o);a[0]=o[0]=1;for(int i=1;i<n;i++)b[i]=g()%P;for(int i=1;i<n;i++)for(int j=1;j<=i;j++)o[i]=(o[i]+1LL*o[i-j]*b[j])%P;s(0,n-1);for(int i=0;i<n;i++)if(a[i]!=o[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
B1='P4721 【模板】分治 FFT'
add('P4721',B1,r'''递推式中，每个已知的 $f_i$ 会给所有更靠后的项贡献 $f_i g_j$。对下标区间做分治：先递归求完左半区，再用一次 NTT 卷积把左半区的所有贡献批量加入右半区，最后递归处理右半区。这样在处理一个区间时，左侧系数已经完全确定。

每层卷积总规模为 $O(n)$，共有 $O(\log n)$ 层，复杂度 $O(n\log^2 n)$，空间复杂度 $O(n)$。''',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},parts=[AB],extra=[('2\n0\n','1 0\n'),('2\n5\n','1 5\n'),('5\n1 0 0 0\n','1 1 1 1 1\n'),('6\n1 1 1 1 1\n','1 1 2 4 8 16\n')])
statement('P4721',B1,r'Given $g_{1\dots n-1}$, find $f_{0\dots n-1}$ where $f_0=1$ and $f_i=\sum_{j=1}^i f_{i-j}g_j$. All operations are modulo $998244353$.',r'The first line contains $n$. The second line contains $n-1$ integers $g_1,\dots,g_{n-1}$.',r'Print $n$ integers $f_0,\dots,f_{n-1}$ modulo $998244353$.',r'$2\le n\le 10^5$ and $0\le g_i<998244353$.')

B=r'''#include <bits/stdc++.h>
using namespace std;const int N=262144,P=998244353,G=3;int a[N],b[N],c[N],d[N],x[N],y[N],r[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,t=1;j<l/2;j++,t=1LL*t*w%P){int u=a[i+j],v=1LL*t*a[i+j+l/2]%P;a[i+j]=(u+v)%P;a[i+j+l/2]=(u-v+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void m(int*a,int n,int*b,int k,int*c,int z){int l=1,h=0;while(l<n+k-1)l<<=1;while((1<<h)<l)h++;for(int i=0;i<l;i++)x[i]=i<n?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(h-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)x[i]=1LL*x[i]*y[i]%P;f(x,l,-1);for(int i=0;i<z;i++)c[i]=x[i];}void h(int*a,int*b,int n){memset(b,0,n*sizeof(int));b[0]=q(a[0]);for(int k=1;k<n;k<<=1){int z=min(k<<1,n),l=1,t=0;while(l<z+k)l<<=1;while((1<<t)<l)t++;for(int i=0;i<l;i++)x[i]=i<z?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(t-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)y[i]=1LL*y[i]*(2-1LL*x[i]*y[i]%P+P)%P;f(y,l,-1);for(int i=0;i<z;i++)b[i]=y[i];}}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];h(a,b,n);for(int i=1;i<n;i++)d[i-1]=1LL*i*a[i]%P;c[0]=0;if(n>1)m(d,n-1,b,n,c+1,n-1);for(int i=1;i<n;i++)c[i]=1LL*c[i]*q(i)%P;for(int i=0;i<n;i++)cout<<c[i]<<' ';cout<<'\n';}
'''
BB=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005,P=998244353;int a[N],b[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];for(int k=1;k<n;k++){long long s=1LL*k*a[k]%P;for(int i=1;i<k;i++)s-=1LL*i*b[i]%P*a[k-i]%P;b[k]=(s%P+P)%P*q(k)%P;}for(int i=0;i<n;i++)cout<<b[i]<<' ';cout<<'\n';}
'''
BG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;mt19937_64 g(s);z=min(100000ULL,max(1ULL,z));int n=g()%z+1;cout<<n<<'\n'<<1<<' ';for(int i=1;i<n;i++)cout<<g()%998244353<<' ';cout<<'\n';}
'''
BS=r'''#include <bits/stdc++.h>
using namespace std;const int N=256,P=998244353,G=3;int a[N],b[N],c[N],d[N],x[N],y[N],r[N],o[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,t=1;j<l/2;j++,t=1LL*t*w%P){int u=a[i+j],v=1LL*t*a[i+j+l/2]%P;a[i+j]=(u+v)%P;a[i+j+l/2]=(u-v+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void m(int*a,int n,int*b,int k,int*c,int z){int l=1,h=0;while(l<n+k-1)l<<=1;while((1<<h)<l)h++;for(int i=0;i<l;i++)x[i]=i<n?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(h-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)x[i]=1LL*x[i]*y[i]%P;f(x,l,-1);for(int i=0;i<z;i++)c[i]=x[i];}void h(int*a,int*b,int n){memset(b,0,n*sizeof(int));b[0]=q(a[0]);for(int k=1;k<n;k<<=1){int z=min(k<<1,n),l=1,t=0;while(l<z+k)l<<=1;while((1<<t)<l)t++;for(int i=0;i<l;i++)x[i]=i<z?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(t-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)y[i]=1LL*y[i]*(2-1LL*x[i]*y[i]%P+P)%P;f(y,l,-1);for(int i=0;i<z;i++)b[i]=y[i];}}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long z=C>2?stoull(v[2]):1;mt19937_64 g(z);while(R--){int n=g()%60+1;memset(a,0,sizeof a);memset(o,0,sizeof o);a[0]=1;for(int i=1;i<n;i++)a[i]=g()%P;for(int k=1;k<n;k++){long long s=1LL*k*a[k]%P;for(int i=1;i<k;i++)s-=1LL*i*o[i]%P*a[k-i]%P;o[k]=(s%P+P)%P*q(k)%P;}h(a,b,n);for(int i=1;i<n;i++)d[i-1]=1LL*i*a[i]%P;c[0]=0;if(n>1)m(d,n-1,b,n,c+1,n-1);for(int i=1;i<n;i++)c[i]=1LL*c[i]*q(i)%P;for(int i=0;i<n;i++)if(c[i]!=o[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
B2='P4725 【模板】多项式对数函数（多项式 ln）'
add('P4725',B2,r'''形式幂级数满足 $(\ln A)'=A'/A$。先用牛顿迭代

$$B\leftarrow B(2-AB)\pmod{x^{2k}}$$

逐倍求出 $A$ 的逆元，再用 NTT 计算 $A'B$，最后逐项积分。常数项为零。

复杂度 $O(n\log n)$，空间复杂度 $O(n)$。''',{'.cpp':B,' 数据生成.cpp':BG,' 暴力.cpp':BB,' 对拍.cpp':BS},parts=[BB],extra=[('1\n1\n','0\n'),('2\n1 1\n','0 1\n'),('5\n1 0 0 0 0\n','0 0 0 0 0\n'),('5\n1 1 0 0 0\n','0 1 499122176 332748118 249561088\n')])
statement('P4725',B2,r'Given a polynomial $A(x)$ of degree at most $n-1$, find $B(x)\equiv\ln A(x)\pmod{x^n}$. Coefficients are taken modulo $998244353$.',r'The first line contains $n$. The second line contains $n$ coefficients $a_0,a_1,\dots,a_{n-1}$. It is guaranteed that $a_0=1$.','Print the $n$ coefficients of $B(x)$ in increasing order of degree.',r'$n\le10^5$ and $0\le a_i<998244353$.')

C=r'''#include <bits/stdc++.h>
using namespace std;const int N=262144,P=998244353,G=3;int a[N],b[N],c[N],d[N],e[N],t[N],x[N],y[N],r[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,u=1;j<l/2;j++,u=1LL*u*w%P){int A=a[i+j],B=1LL*u*a[i+j+l/2]%P;a[i+j]=(A+B)%P;a[i+j+l/2]=(A-B+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void m(int*a,int n,int*b,int k,int*c,int z){int l=1,h=0;while(l<n+k-1)l<<=1;while((1<<h)<l)h++;for(int i=0;i<l;i++)x[i]=i<n?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(h-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)x[i]=1LL*x[i]*y[i]%P;f(x,l,-1);for(int i=0;i<z;i++)c[i]=x[i];}void h(int*a,int*b,int n){memset(b,0,n*sizeof(int));b[0]=q(a[0]);for(int k=1;k<n;k<<=1){int z=min(k<<1,n),l=1,u=0;while(l<z+k)l<<=1;while((1<<u)<l)u++;for(int i=0;i<l;i++)x[i]=i<z?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(u-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)y[i]=1LL*y[i]*(2-1LL*x[i]*y[i]%P+P)%P;f(y,l,-1);for(int i=0;i<z;i++)b[i]=y[i];}}void l(int*a,int*b,int n){h(a,d,n);b[0]=0;if(n>1){for(int i=1;i<n;i++)e[i-1]=1LL*i*a[i]%P;m(e,n-1,d,n,b+1,n-1);for(int i=1;i<n;i++)b[i]=1LL*b[i]*q(i)%P;}}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];b[0]=1;for(int k=1;k<n;k<<=1){int z=min(k<<1,n);l(b,c,z);for(int i=0;i<z;i++)c[i]=(a[i]-c[i]+P)%P;c[0]=(c[0]+1)%P;m(b,k,c,z,t,z);for(int i=0;i<z;i++)b[i]=t[i];}for(int i=0;i<n;i++)cout<<b[i]<<' ';cout<<'\n';}
'''
CB=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005,P=998244353;int a[N],b[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];b[0]=1;for(int k=1;k<n;k++){long long s=0;for(int i=1;i<=k;i++)s+=1LL*i*a[i]%P*b[k-i]%P;b[k]=s%P*q(k)%P;}for(int i=0;i<n;i++)cout<<b[i]<<' ';cout<<'\n';}
'''
CG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;mt19937_64 g(s);z=min(100000ULL,max(1ULL,z));int n=g()%z+1;cout<<n<<'\n'<<0<<' ';for(int i=1;i<n;i++)cout<<g()%998244353<<' ';cout<<'\n';}
'''
CS=r'''#include <bits/stdc++.h>
using namespace std;const int N=256,P=998244353,G=3;int a[N],b[N],c[N],d[N],e[N],t[N],x[N],y[N],r[N],o[N];int q(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int z){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=q(G,(P-1)/l);if(z<0)w=q(w);for(int i=0;i<n;i+=l)for(int j=0,u=1;j<l/2;j++,u=1LL*u*w%P){int A=a[i+j],B=1LL*u*a[i+j+l/2]%P;a[i+j]=(A+B)%P;a[i+j+l/2]=(A-B+P)%P;}}if(z<0){int w=q(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void m(int*a,int n,int*b,int k,int*c,int z){int l=1,h=0;while(l<n+k-1)l<<=1;while((1<<h)<l)h++;for(int i=0;i<l;i++)x[i]=i<n?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(h-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)x[i]=1LL*x[i]*y[i]%P;f(x,l,-1);for(int i=0;i<z;i++)c[i]=x[i];}void h(int*a,int*b,int n){memset(b,0,n*sizeof(int));b[0]=q(a[0]);for(int k=1;k<n;k<<=1){int z=min(k<<1,n),l=1,u=0;while(l<z+k)l<<=1;while((1<<u)<l)u++;for(int i=0;i<l;i++)x[i]=i<z?a[i]:0,y[i]=i<k?b[i]:0,r[i]=(r[i>>1]>>1)|((i&1)<<(u-1));f(x,l,1);f(y,l,1);for(int i=0;i<l;i++)y[i]=1LL*y[i]*(2-1LL*x[i]*y[i]%P+P)%P;f(y,l,-1);for(int i=0;i<z;i++)b[i]=y[i];}}void l(int*a,int*b,int n){h(a,d,n);b[0]=0;if(n>1){for(int i=1;i<n;i++)e[i-1]=1LL*i*a[i]%P;m(e,n-1,d,n,b+1,n-1);for(int i=1;i<n;i++)b[i]=1LL*b[i]*q(i)%P;}}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long z=C>2?stoull(v[2]):1;mt19937_64 g(z);while(R--){int n=g()%60+1;memset(a,0,sizeof a);memset(b,0,sizeof b);memset(o,0,sizeof o);for(int i=1;i<n;i++)a[i]=g()%P;o[0]=1;for(int k=1;k<n;k++){long long s=0;for(int i=1;i<=k;i++)s+=1LL*i*a[i]%P*o[k-i]%P;o[k]=s%P*q(k)%P;}b[0]=1;for(int k=1;k<n;k<<=1){int z=min(k<<1,n);l(b,c,z);for(int i=0;i<z;i++)c[i]=(a[i]-c[i]+P)%P;c[0]=(c[0]+1)%P;m(b,k,c,z,t,z);for(int i=0;i<z;i++)b[i]=t[i];}for(int i=0;i<n;i++)if(b[i]!=o[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
B3='P4726 【模板】多项式指数函数（多项式 exp）'
add('P4726',B3,r'''设当前 $B\equiv e^A\pmod{x^k}$。方程 $\ln B=A$ 的牛顿迭代为

$$B\leftarrow B(1+A-\ln B)\pmod{x^{2k}}.$$

从 $B_0=1$ 开始，每轮用多项式求逆、求导、NTT 乘法和积分算出 $\ln B$，使正确项数翻倍，直到覆盖前 $n$ 项。

复杂度 $O(n\log n)$，空间复杂度 $O(n)$。''',{'.cpp':C,' 数据生成.cpp':CG,' 暴力.cpp':CB,' 对拍.cpp':CS},parts=[CB],extra=[('1\n0\n','1\n'),('2\n0 1\n','1 1\n'),('5\n0 0 0 0 0\n','1 0 0 0 0\n'),('5\n0 1 0 0 0\n','1 1 499122177 166374059 291154603\n')])
statement('P4726',B3,r'Given a polynomial $A(x)$ of degree at most $n-1$, find $B(x)\equiv e^{A(x)}\pmod{x^n}$. Coefficients are taken modulo $998244353$.',r'The first line contains $n$. The second line contains $n$ coefficients $a_0,a_1,\dots,a_{n-1}$. It is guaranteed that $a_0=0$.','Print the $n$ coefficients of $B(x)$ in increasing order of degree.',r'$n\le10^5$ and $0\le a_i<998244353$.')
