from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=1005;struct Q{unsigned long long x;int w;}a[N];unsigned long long b[64];int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i].x>>a[i].w;sort(a,a+n,[](Q x,Q y){return x.w>y.w;});long long r=0;for(int j=0;j<n;j++){auto x=a[j].x;for(int i=63;i>=0;i--)if(x>>i&1){if(b[i])x^=b[i];else{b[i]=x;r+=a[j].w;break;}}}cout<<r<<'\n';}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=25;unsigned long long a[N],b[64];int w[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i]>>w[i];long long z=0;for(int s=0;s<(1<<n);s++){memset(b,0,sizeof b);long long q=0;bool f=1;for(int j=0;j<n&&f;j++)if(s>>j&1){auto x=a[j];bool k=0;q+=w[j];for(int i=63;i>=0;i--)if(x>>i&1){if(b[i])x^=b[i];else{b[i]=x;k=1;break;}}if(!k)f=0;}if(f)z=max(z,q);}cout<<z<<'\n';}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int n=g()%min(1000ULL,max(1ULL,z))+1;cout<<n<<'\n';while(n--)cout<<(g()%1000000000000000000ULL+1)<<' '<<g()%10000+1<<'\n';}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const int N=18;unsigned long long a[N],b[64],c[64];int w[N],o[N];int main(int z,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=z>1?stoi(v[1]):1000;unsigned long long s=z>2?stoull(v[2]):1;mt19937_64 g(s);while(R--){int n=g()%14+1;for(int i=0;i<n;i++)a[i]=g()%1024+1,w[i]=g()%100+1;iota(o,o+n,0);sort(o,o+n,[](int x,int y){return w[x]>w[y];});memset(b,0,sizeof b);long long x=0,y=0;for(int j=0;j<n;j++){auto q=a[o[j]];for(int i=63;i>=0;i--)if(q>>i&1){if(b[i])q^=b[i];else{b[i]=q;x+=w[o[j]];break;}}}for(int m=0;m<(1<<n);m++){memset(c,0,sizeof c);long long q=0;bool f=1;for(int j=0;j<n&&f;j++)if(m>>j&1){auto t=a[j];bool k=0;q+=w[j];for(int i=63;i>=0;i--)if(t>>i&1){if(c[i])t^=c[i];else{c[i]=t;k=1;break;}}if(!k)f=0;}if(f)y=max(y,q);}if(x!=y)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P4570','P4570 [BJWC2011] 元素',r'把矿石按魔力从大到小排序，依次尝试加入异或线性基。线性无关集合构成线性拟阵，因此该贪心得到最大权独立集。时间复杂度 $O(64N+N\log N)$。',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},extra=[('1\n7 9\n','9\n'),('3\n1 5\n2 4\n3 100\n','105\n'),('4\n1 1\n2 2\n4 4\n7 20\n','26\n')])

B=r'''#include <bits/stdc++.h>
using namespace std;const int N=20005,L=15;unsigned long long a[N],b[N][61],c[61];int h[N],to[N*2],nx[N*2],p[N][L],d[N],z[N][61],q[N],e;void I(unsigned long long*x,int*y,unsigned long long v,int k){for(int i=60;i>=0;i--)if(v>>i&1){if(!x[i]){x[i]=v;y[i]=k;return;}if(y[i]<k)swap(y[i],k),swap(x[i],v);v^=x[i];}}void J(unsigned long long v){for(int i=60;i>=0;i--)if(v>>i&1){if(c[i])v^=c[i];else{c[i]=v;return;}}}int lca(int x,int y){if(d[x]<d[y])swap(x,y);for(int i=L-1;i>=0;i--)if(d[p[x][i]]>=d[y])x=p[x][i];if(x==y)return x;for(int i=L-1;i>=0;i--)if(p[x][i]!=p[y][i])x=p[x][i],y=p[y][i];return p[x][0];}int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m;cin>>n>>m;for(int i=1;i<=n;i++)cin>>a[i];for(int i=1,u,v;i<n;i++){cin>>u>>v;to[++e]=v;nx[e]=h[u];h[u]=e;to[++e]=u;nx[e]=h[v];h[v]=e;}int l=0,r=1;q[0]=1;d[1]=1;while(l<r){int u=q[l++];for(int i=h[u];i;i=nx[i])if(to[i]!=p[u][0])p[to[i]][0]=u,d[to[i]]=d[u]+1,q[r++]=to[i];}for(int k=0;k<n;k++){int u=q[k],v=p[u][0];memcpy(b[u],b[v],sizeof b[u]);memcpy(z[u],z[v],sizeof z[u]);I(b[u],z[u],a[u],d[u]);for(int j=1;j<L;j++)p[u][j]=p[p[u][j-1]][j-1];}while(m--){int x,y;cin>>x>>y;int t=lca(x,y);memset(c,0,sizeof c);for(int i=60;i>=0;i--){if(z[x][i]>=d[t])J(b[x][i]);if(z[y][i]>=d[t])J(b[y][i]);}unsigned long long s=0;for(int i=60;i>=0;i--)s=max(s,s^c[i]);cout<<s<<'\n';}}
'''
BB=r'''#include <bits/stdc++.h>
using namespace std;const int N=1005;unsigned long long a[N],b[61];int h[N],to[N*2],nx[N*2],p[N],q[N],e;int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m;cin>>n>>m;for(int i=1;i<=n;i++)cin>>a[i];for(int i=1,u,v;i<n;i++){cin>>u>>v;to[++e]=v;nx[e]=h[u];h[u]=e;to[++e]=u;nx[e]=h[v];h[v]=e;}while(m--){int x,y,l=0,r=1;q[0]=x;memset(p,0,sizeof p);p[x]=-1;while(l<r&&q[l]!=y){int u=q[l++];for(int i=h[u];i;i=nx[i])if(!p[to[i]])p[to[i]]=u,q[r++]=to[i];}memset(b,0,sizeof b);for(int u=y;u!=-1;u=p[u]){auto v=a[u];for(int i=60;i>=0;i--)if(v>>i&1){if(b[i])v^=b[i];else{b[i]=v;break;}}}unsigned long long s=0;for(int i=60;i>=0;i--)s=max(s,s^b[i]);cout<<s<<'\n';}}
'''
BG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int n=g()%min(20000ULL,max(1ULL,z))+1,m=g()%min(200000ULL,max(1ULL,z))+1;cout<<n<<' '<<m<<'\n';for(int i=1;i<=n;i++)cout<<(g()&((1ULL<<60)-1))<<' ';cout<<'\n';for(int i=2;i<=n;i++)cout<<i<<' '<<g()%(i-1)+1<<'\n';while(m--)cout<<g()%n+1<<' '<<g()%n+1<<'\n';}
'''
BS=r'''#include <bits/stdc++.h>
using namespace std;const int N=30;unsigned long long a[N],b[N][61],c[61],t[61];int p[N],d[N],z[N][61];void I(unsigned long long*x,int*y,unsigned long long v,int k){for(int i=60;i>=0;i--)if(v>>i&1){if(!x[i]){x[i]=v;y[i]=k;return;}if(y[i]<k)swap(y[i],k),swap(x[i],v);v^=x[i];}}void J(unsigned long long*x,unsigned long long v){for(int i=60;i>=0;i--)if(v>>i&1){if(x[i])v^=x[i];else{x[i]=v;return;}}}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long s=C>2?stoull(v[2]):1;mt19937_64 g(s);while(R--){int n=g()%20+1;memset(b,0,sizeof b);memset(z,0,sizeof z);d[1]=1;p[1]=0;for(int i=1;i<=n;i++){a[i]=g()%4096;if(i>1)p[i]=g()%(i-1)+1,d[i]=d[p[i]]+1;memcpy(b[i],b[p[i]],sizeof b[i]);memcpy(z[i],z[p[i]],sizeof z[i]);I(b[i],z[i],a[i],d[i]);}for(int Q=0;Q<20;Q++){int x=g()%n+1,y=g()%n+1,u=x,w=y;while(d[u]>d[w])u=p[u];while(d[w]>d[u])w=p[w];while(u!=w)u=p[u],w=p[w];int l=u;memset(c,0,sizeof c);for(int i=60;i>=0;i--){if(z[x][i]>=d[l])J(c,b[x][i]);if(z[y][i]>=d[l])J(c,b[y][i]);}unsigned long long A=0;for(int i=60;i>=0;i--)A=max(A,A^c[i]);memset(t,0,sizeof t);for(u=x;u!=l;u=p[u])J(t,a[u]);for(u=y;u!=l;u=p[u])J(t,a[u]);J(t,a[l]);unsigned long long B=0;for(int i=60;i>=0;i--)B=max(B,B^t[i]);if(A!=B)return cout<<"WA\n",1;}}cout<<"OK\n";}
'''
add('P3292','P3292 [SCOI2016] 幸运数字',r'从根向下维护带深度标记的前缀线性基：同一主元优先保留深度更大的向量。查询路径 $x\to y$ 时，取两端线性基中标记深度不小于 $\operatorname{depth}(\operatorname{lca})$ 的向量合并，再贪心求最大异或值。预处理 $O(60N\log N)$，单次询问 $O(60^2+\log N)$。',{'.cpp':B,' 数据生成.cpp':BG,' 暴力.cpp':BB,' 对拍.cpp':BS},extra=[('1 2\n7\n1 1\n1 1\n','7\n7\n'),('3 2\n1 2 4\n1 2\n2 3\n1 3\n2 2\n','7\n2\n'),('4 2\n3 5 6 9\n1 2\n1 3\n3 4\n2 4\n1 3\n','15\n6\n')])

C=r'''#include <bits/stdc++.h>
using namespace std;const int N=50005,M=200005;int h[N],to[M],nx[M],q[N],e;unsigned long long w[M],d[N],b[64];bool v[N];void I(unsigned long long x){for(int i=63;i>=0;i--)if(x>>i&1){if(b[i])x^=b[i];else{b[i]=x;return;}}}int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m;cin>>n>>m;while(m--){int x,y;unsigned long long z;cin>>x>>y>>z;to[++e]=y;w[e]=z;nx[e]=h[x];h[x]=e;to[++e]=x;w[e]=z;nx[e]=h[y];h[y]=e;}int l=0,r=1;q[0]=1;v[1]=1;while(l<r){int x=q[l++];for(int i=h[x];i;i=nx[i])if(!v[to[i]])v[to[i]]=1,d[to[i]]=d[x]^w[i],q[r++]=to[i];else I(d[x]^d[to[i]]^w[i]);}unsigned long long s=d[n];for(int i=63;i>=0;i--)s=max(s,s^b[i]);cout<<s<<'\n';}
'''
CB=r'''#include <bits/stdc++.h>
using namespace std;const int N=105,M=2005,K=16384;int h[N],to[M],nx[M],w[M],x[N*K],y[N*K],e;bool v[N][K];int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m;cin>>n>>m;while(m--){int a,b,c;cin>>a>>b>>c;to[++e]=b;w[e]=c;nx[e]=h[a];h[a]=e;to[++e]=a;w[e]=c;nx[e]=h[b];h[b]=e;}int l=0,r=1;v[1][0]=1;while(l<r){int a=x[l],b=y[l++];for(int i=h[a];i;i=nx[i])if(!v[to[i]][b^w[i]])v[to[i]][b^w[i]]=1,x[r]=to[i],y[r++]=b^w[i];}for(int i=K-1;i>=0;i--)if(v[n][i])return cout<<i<<'\n',0;}
'''
CG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int n=g()%min(50000ULL,max(2ULL,z))+2,m=n-1+g()%max(1,n);cout<<n<<' '<<m<<'\n';for(int i=2;i<=n;i++)cout<<i<<' '<<g()%(i-1)+1<<' '<<(g()&((1ULL<<60)-1))<<'\n';for(int i=n-1;i<m;i++)cout<<g()%n+1<<' '<<g()%n+1<<' '<<(g()&((1ULL<<60)-1))<<'\n';}
'''
CS=r'''#include <bits/stdc++.h>
using namespace std;const int N=20,M=100;int h[N],to[M],nx[M],w[M],q[N*128],z[N*128],e;unsigned long long d[N],b[64];bool V[N],s[N][128];void I(unsigned long long x){for(int i=63;i>=0;i--)if(x>>i&1){if(b[i])x^=b[i];else{b[i]=x;return;}}}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long S=C>2?stoull(v[2]):1;mt19937_64 g(S);while(R--){int n=g()%10+2,m=n-1+g()%15;e=0;memset(h,0,sizeof h);memset(V,0,sizeof V);memset(b,0,sizeof b);memset(s,0,sizeof s);auto E=[&](int x,int y,int k){to[++e]=y;w[e]=k;nx[e]=h[x];h[x]=e;to[++e]=x;w[e]=k;nx[e]=h[y];h[y]=e;};for(int i=2;i<=n;i++)E(i,g()%(i-1)+1,g()%64);while(e/2<m)E(g()%n+1,g()%n+1,g()%64);int l=0,r=1;q[0]=1;V[1]=1;while(l<r){int x=q[l++];for(int i=h[x];i;i=nx[i])if(!V[to[i]])V[to[i]]=1,d[to[i]]=d[x]^w[i],q[r++]=to[i];else I(d[x]^d[to[i]]^w[i]);}unsigned long long A=d[n];for(int i=63;i>=0;i--)A=max(A,A^b[i]);l=0;r=1;q[0]=1;z[0]=0;s[1][0]=1;while(l<r){int x=q[l],k=z[l++];for(int i=h[x];i;i=nx[i])if(!s[to[i]][k^w[i]])s[to[i]][k^w[i]]=1,q[r]=to[i],z[r++]=k^w[i];}int B=127;while(!s[n][B])B--;if(A!=(unsigned)B)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P4151','P4151 [WC2011] 最大 XOR 和路径',r'先求一棵生成树上的根异或距离 $d_u$。每条边产生一个环异或值 $d_u\oplus d_v\oplus w$，把这些值加入线性基；任意从 $1$ 到 $N$ 的游走等价于树路径异或值再异或若干环，最后从高位到低位贪心增大答案。时间复杂度 $O((N+M)\cdot64)$。',{'.cpp':C,' 数据生成.cpp':CG,' 暴力.cpp':CB,' 对拍.cpp':CS},parts=[CB],extra=[('2 1\n1 2 7\n','7\n'),('3 3\n1 2 1\n2 3 2\n1 3 4\n','4\n'),('2 2\n1 2 5\n1 1 7\n','5\n')])
