from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005;long long a[N],p[N],w[N],b[N];long long e(long long a,long long b,long long&x,long long&y){if(!b)return x=1,y=0,a;long long d=e(b,a%b,y,x);y-=a/b*x;return d;}bool m(long long&r,long long&q,long long x,long long y){long long u,v,g=e(q,y,u,v),d=x-r;if(d%g)return 0;long long z=y/g,t=(__int128)(d/g)*u%z;r=(r+(__int128)q*((t+z)%z))%(q*z);q*=z;return 1;}int main(){ios::sync_with_stdio(0);cin.tie(0);int T;cin>>T;while(T--){int n,k;cin>>n>>k;for(int i=0;i<n;i++)cin>>a[i];for(int i=0;i<n;i++)cin>>p[i];for(int i=0;i<n;i++)cin>>w[i];multiset<long long>s;while(k--){long long x;cin>>x;s.insert(x);}for(int i=0;i<n;i++){auto t=s.upper_bound(a[i]);if(t==s.begin())t=s.begin();else --t;b[i]=*t;s.erase(t);s.insert(w[i]);}long long r=0,q=1,z=0;bool f=1;for(int i=0;i<n;i++){z=max(z,(a[i]+b[i]-1)/b[i]);long long x,y,g=e(b[i],p[i],x,y);if(a[i]%g){f=0;break;}long long v=p[i]/g,u=(__int128)(a[i]/g)*x%v;if(!m(r,q,(u+v)%v,v)){f=0;break;}}if(!f){cout<<-1<<'\n';continue;}if(r<z)r+=(z-r+q-1)/q*q;cout<<r<<'\n';}}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=105;long long a[N],p[N],w[N],b[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int T;cin>>T;while(T--){int n,m;cin>>n>>m;for(int i=0;i<n;i++)cin>>a[i];for(int i=0;i<n;i++)cin>>p[i];for(int i=0;i<n;i++)cin>>w[i];multiset<long long>s;while(m--){long long x;cin>>x;s.insert(x);}for(int i=0;i<n;i++){auto t=s.upper_bound(a[i]);if(t==s.begin())t=s.begin();else --t;b[i]=*t;s.erase(t);s.insert(w[i]);}long long x;for(x=0;x<=10000000;x++){int i=0;for(;i<n;i++)if(b[i]*x<a[i]||(b[i]*x-a[i])%p[i])break;if(i==n)break;}cout<<(x<=10000000?x:-1)<<'\n';}}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int n=g()%min(100000ULL,max(1ULL,z))+1,m=g()%min(20,n)+1;cout<<1<<'\n'<<n<<' '<<m<<'\n';for(int i=0;i<n;i++)cout<<g()%100+1<<' ';cout<<'\n';for(int i=0;i<n;i++)cout<<g()%10+1<<' ';cout<<'\n';for(int i=0;i<n;i++)cout<<g()%100+1<<' ';cout<<'\n';while(m--)cout<<g()%100+1<<' ';cout<<'\n';}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;long long a[6],p[6],w[6],b[6];long long e(long long a,long long b,long long&x,long long&y){if(!b)return x=1,y=0,a;long long d=e(b,a%b,y,x);y-=a/b*x;return d;}bool m(long long&r,long long&q,long long x,long long y){long long u,v,g=e(q,y,u,v),d=x-r;if(d%g)return 0;long long z=y/g,t=(__int128)(d/g)*u%z;r=(r+(__int128)q*((t+z)%z))%(q*z);q*=z;return 1;}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long z=C>2?stoull(v[2]):1;mt19937_64 g(z);while(R--){int n=g()%5+1,k=g()%5+1;multiset<long long>s;for(int i=0;i<n;i++)a[i]=g()%50+1,p[i]=g()%10+1,w[i]=g()%20+1;for(int i=0;i<k;i++)s.insert(g()%20+1);for(int i=0;i<n;i++){auto t=s.upper_bound(a[i]);if(t==s.begin())t=s.begin();else --t;b[i]=*t;s.erase(t);s.insert(w[i]);}long long r=0,q=1,h=0,A=-1;bool f=1;for(int i=0;i<n;i++){h=max(h,(a[i]+b[i]-1)/b[i]);long long x,y,d=e(b[i],p[i],x,y);if(a[i]%d){f=0;break;}long long M=p[i]/d,u=(__int128)(a[i]/d)*x%M;if(!m(r,q,(u+M)%M,M)){f=0;break;}}if(f){if(r<h)r+=(h-r+q-1)/q*q;A=r;}long long B=-1;for(long long x=0;x<=10000;x++){int i=0;for(;i<n;i++)if(b[i]*x<a[i]||(b[i]*x-a[i])%p[i])break;if(i==n){B=x;break;}}if(A!=B)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
P1=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005;long long a[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int T;cin>>T;while(T--){int n,m;cin>>n>>m;for(int i=0;i<n;i++)cin>>a[i];long long x;for(int i=0;i<n;i++)cin>>x;for(int i=0;i<n;i++)cin>>x;while(m--)cin>>x;cout<<*max_element(a,a+n)<<'\n';}}
'''
add('P4774','P4774 [NOI2018] 屠龙勇士',r'''先用有序集合严格模拟机器人的选剑过程，得到每条龙实际使用的攻击力 $b_i$。

杀死第 $i$ 条龙要求 $b_ix\ge a_i$ 且 $b_ix\equiv a_i\pmod {p_i}$。线性同余先除以 $\gcd(b_i,p_i)$，无解时立即结束；其余同余式用扩展 CRT 合并。最后在所得同余类中取不小于所有 $\lceil a_i/b_i\rceil$ 的最小值。''',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},parts=[P1,AB],extra=[('2\n1 1\n5\n3\n1\n2\n1 1\n6\n4\n1\n2\n','4\n3\n'),('1\n1 1\n5\n4\n1\n2\n','-1\n'),('1\n1 1\n1\n1\n1\n1\n','1\n')])

B=r'''#include <bits/stdc++.h>
using namespace std;const int V=10000005,S=3205,U=1000000000;int h[V],t[S],x[1005],z[1005];long long e(long long a,long long b,long long&x,long long&y){if(!b)return x=1,y=0,a;long long d=e(b,a%b,y,x);y-=a/b*x;return d;}int b(int a,int c,int m){int s=sqrt(m-1)+1,A=1%m,z=0,r=-1;for(int i=0;i<s;i++)h[t[z++]=1LL*c*A%m]=i,A=1LL*A*a%m;int C=1%m;for(int i=1;i<=s&&r<0;i++)if(h[C=1LL*C*A%m]>=0)r=i*s-h[C];while(z)h[t[--z]]=-1;return r;}pair<int,int> q(int a,int c,int m){if(m==1)return {0,1};int o=0,A=1%m,d=1;long long X,Y;for(;;){int z=__gcd((long long)A*a%m,(long long)m);if(z==d)break;if(A==c)return {o,-1};o++;A=1LL*A*a%m;d=z;}if(c%d)return {-1,-1};m/=d;c/=d;A/=d;e(A,m,X,Y);c=1LL*c*((X%m+m)%m)%m;int v=b(a,c,m);if(v<0)return {-1,-1};int y=b(a,1%m,m);return {v%y+o,y};}bool m(long long&a,long long&n,long long b,long long p){long long x,y,g=e(n,p,x,y),d=b-a;if(d%g)return 0;long long z=p/g,k=(__int128)(d/g)*x%z;a=(a+(__int128)n*((k+z)%z))%(n*z);n*=z;return 1;}int main(){ios::sync_with_stdio(0);cin.tie(0);memset(h,-1,sizeof h);int n,X=-1,M=0;long long P=0,Q=1;cin>>n;for(int i=0,k,g,r;i<n;i++){cin>>k>>g>>r;auto a=q(k%g,r%g,g);x[i]=a.first;z[i]=a.second;if(x[i]<0)return cout<<"Impossible\n",0;if(z[i]<0)X=x[i];M=max(M,x[i]);}if(X>=0){for(int i=0;i<n;i++)if((z[i]<0&&X!=x[i])||(z[i]>=0&&(X<x[i]||(X-x[i])%z[i])))return cout<<"Impossible\n",0;return cout<<X<<'\n',0;}for(int i=0;i<n;i++){if(Q>U){if((P-x[i])%z[i])return cout<<"Impossible\n",0;}else if(!m(P,Q,x[i]%z[i],z[i]))return cout<<"Impossible\n",0;}if(P<M){if(Q>U)return cout<<"Impossible\n",0;P+=(M-P+Q-1)/Q*Q;}if(P>U)cout<<"Impossible\n";else cout<<P<<'\n';}
'''
BB=r'''#include <bits/stdc++.h>
using namespace std;const int N=1005;long long k[N],g[N],r[N],w[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>k[i]>>g[i]>>r[i],w[i]=1;for(int d=0;d<=1000000000;d++){int i=0;for(;i<n;i++)if(w[i]!=r[i])break;if(i==n)return cout<<d<<'\n',0;for(i=0;i<n;i++)w[i]=w[i]*k[i]%g[i],w[i]+=!w[i]*g[i];}cout<<"Impossible\n";}
'''
BG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 q(s);int n=q()%min(1000ULL,max(1ULL,z))+1,d=q()%1000;cout<<n<<'\n';while(n--){long long g=q()%10000000+1,k=q()%g+1,r=1;for(int i=0;i<d;i++)r=r*k%g;r+=!r*g;cout<<k<<' '<<g<<' '<<r<<'\n';}}
'''
BS=r'''#include <bits/stdc++.h>
using namespace std;const int V=105,S=20;int h[V],t[S],k[6],g[6],r[6],x[6],z[6];long long e(long long a,long long b,long long&x,long long&y){if(!b)return x=1,y=0,a;long long d=e(b,a%b,y,x);y-=a/b*x;return d;}int b(int a,int c,int m){int s=sqrt(m-1)+1,A=1%m,z=0,r=-1;for(int i=0;i<s;i++)h[t[z++]=1LL*c*A%m]=i,A=1LL*A*a%m;int C=1%m;for(int i=1;i<=s&&r<0;i++)if(h[C=1LL*C*A%m]>=0)r=i*s-h[C];while(z)h[t[--z]]=-1;return r;}pair<int,int> q(int a,int c,int m){if(m==1)return {0,1};int o=0,A=1%m,d=1;long long X,Y;for(;;){int z=__gcd((long long)A*a%m,(long long)m);if(z==d)break;if(A==c)return {o,-1};o++;A=1LL*A*a%m;d=z;}if(c%d)return {-1,-1};m/=d;c/=d;A/=d;e(A,m,X,Y);c=1LL*c*((X%m+m)%m)%m;int v=b(a,c,m);if(v<0)return {-1,-1};int y=b(a,1%m,m);return {v%y+o,y};}bool m(long long&a,long long&n,long long b,long long p){long long x,y,G=e(n,p,x,y),d=b-a;if(d%G)return 0;long long z=p/G,k=(__int128)(d/G)*x%z;a=(a+(__int128)n*((k+z)%z))%(n*z);n*=z;return 1;}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);memset(h,-1,sizeof h);int R=C>1?stoi(v[1]):1000;unsigned long long s=C>2?stoull(v[2]):1;mt19937_64 G(s);while(R--){int n=G()%5+1,d=G()%50,X=-1,M=0;long long P=0,Q=1;bool f=1;for(int i=0;i<n;i++){g[i]=G()%49+2;k[i]=G()%g[i];long long w=1%g[i];for(int j=0;j<d;j++)w=w*k[i]%g[i];r[i]=w;auto a=q(k[i],r[i],g[i]);x[i]=a.first;z[i]=a.second;if(x[i]<0)f=0;if(z[i]<0)X=x[i];M=max(M,x[i]);}long long A=-1;if(f&&X>=0){f=1;for(int i=0;i<n;i++)if((z[i]<0&&X!=x[i])||(z[i]>=0&&(X<x[i]||(X-x[i])%z[i])))f=0;if(f)A=X;}else if(f){for(int i=0;i<n;i++)if(!m(P,Q,x[i]%z[i],z[i]))f=0;if(f){if(P<M)P+=(M-P+Q-1)/Q*Q;A=P;}}long long B=-1;for(int y=0;y<=2000;y++){int i=0;for(;i<n;i++){long long w=1%g[i];for(int j=0;j<y;j++)w=w*k[i]%g[i];if(w!=r[i])break;}if(i==n){B=y;break;}}if(A!=B)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P5345','P5345 【XR-1】快乐肥宅',r'''每天的体重等价于 $k_i^x\bmod g_i$，其中余数零按题意表示为 $g_i$。

对每个方程沿幂序列先剥离长度不超过 $O(\log g_i)$ 的尾部。若目标落在尾部，解唯一；否则约去稳定的 gcd 后用 BSGS 求循环中的最小解和乘法阶，得到 $x\equiv a_i\pmod {q_i}$ 且 $x\ge a_i$。唯一解直接逐式验证，其余用扩展 CRT 合并，再满足所有下界并检查 $10^9$ 限制。''',{'.cpp':B,' 数据生成.cpp':BG,' 暴力.cpp':BB,' 对拍.cpp':BS},parts=[BB])

C=r'''#include <bits/stdc++.h>
using namespace std;const int N=200005,K=100005,Z=3000005;int a[N],p[N],h[N],to[N],nx[N],f[N][10],fc[N],o[N][10],q[K],u[K],v[K],g[K][10],gc[K],c[Z],la[Z],an[N],de[N],sn[N*2],ss[N*2],pr[5000],sv[46350],pc;void F(int x,int*y,int&k){k=0;for(int j=0;j<pc&&1LL*pr[j]*pr[j]<=x;j++)if(x%pr[j]==0){y[k++]=pr[j];while(x%pr[j]==0)x/=pr[j];}if(x>1)y[k++]=x;}void B(int n,int r){int z=0;sn[z]=r;ss[z++]=1;while(z){int x=sn[--z],s=ss[z];if(s>0){de[x]=p[x]?de[p[x]]+1:1;an[x]=-1;for(int i=0;i<fc[x];i++){int y=la[f[x][i]];o[x][i]=y;if(y&&(!~an[x]||de[y]>de[an[x]]))an[x]=y;la[f[x][i]]=x;}sn[z]=x;ss[z++]=-1;for(int y=h[x];y;y=nx[y])sn[z]=to[y],ss[z++]=1;}else for(int i=0;i<fc[x];i++)la[f[x][i]]=o[x][i];}}int main(){ios::sync_with_stdio(0);cin.tie(0);int n,k,z=0,e=0,r=0;for(int i=2;i<=46340;i++)if(!sv[i]){pr[pc++]=i;if(1LL*i*i<=46340)for(int j=i*i;j<=46340;j+=i)sv[j]=1;}cin>>n>>k;for(int i=1;i<=n;i++){cin>>a[i];F(a[i],f[i],fc[i]);for(int j=0;j<fc[i];j++)c[z++]=f[i][j];}for(int i=1,x,y;i<n;i++){cin>>x>>y;p[y]=x;to[++e]=y;nx[e]=h[x];h[x]=e;}for(int i=1;i<=n;i++)if(!p[i])r=i;for(int i=0;i<k;i++){cin>>q[i]>>u[i];if(q[i]==2){cin>>v[i];F(v[i],g[i],gc[i]);for(int j=0;j<gc[i];j++)c[z++]=g[i][j];}}sort(c,c+z);z=unique(c,c+z)-c;for(int i=1;i<=n;i++)for(int j=0;j<fc[i];j++)f[i][j]=lower_bound(c,c+z,f[i][j])-c+1;for(int i=0;i<k;i++)for(int j=0;j<gc[i];j++)g[i][j]=lower_bound(c,c+z,g[i][j])-c+1;B(n,r);for(int i=0;i<k;i++)if(q[i]==1)cout<<an[u[i]]<<'\n';else{a[u[i]]=v[i];fc[u[i]]=gc[i];for(int j=0;j<gc[i];j++)f[u[i]][j]=g[i][j];B(n,r);}}
'''
CB=r'''#include <bits/stdc++.h>
using namespace std;const int N=205;int a[N],p[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n,k;cin>>n>>k;for(int i=1;i<=n;i++)cin>>a[i];for(int i=1,x,y;i<n;i++)cin>>x>>y,p[y]=x;while(k--){int t,u,x;cin>>t>>u;if(t==2)cin>>x,a[u]=x;else{int v=p[u];while(v&&__gcd(a[u],a[v])==1)v=p[v];cout<<(v?v:-1)<<'\n';}}}
'''
CG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100;mt19937_64 g(s);int n=g()%min(200000ULL,max(2ULL,z)-1)+2,k=g()%min(1000ULL,max(1ULL,z))+1;cout<<n<<' '<<k<<'\n';for(int i=1;i<=n;i++)cout<<g()%100000+1<<' ';cout<<'\n';for(int i=2;i<=n;i++)cout<<g()%(i-1)+1<<' '<<i<<'\n';int m=0;while(k--){int t=m<50&&g()%10==0?2:1,u=g()%n+1;cout<<t<<' '<<u;if(t==2)cout<<' '<<g()%100000+1,m++;cout<<'\n';}}
'''
CS=r'''#include <bits/stdc++.h>
using namespace std;const int N=105;int a[N],p[N],an[N];int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long s=C>2?stoull(v[2]):1;mt19937_64 g(s);while(R--){int n=g()%100+1;for(int i=1;i<=n;i++)a[i]=g()%1000+1,p[i]=i==1?0:g()%(i-1)+1;for(int i=1;i<=n;i++){int x=p[i];while(x&&__gcd(a[i],a[x])==1)x=p[x];an[i]=x?x:-1;}for(int i=1;i<=n;i++){int x=p[i];while(x&&__gcd(a[i],a[x])==1)x=p[x];if(an[i]!=(x?x:-1))return cout<<"WA\n",1;}int u=g()%n+1;a[u]=g()%1000+1;for(int i=1;i<=n;i++){int x=p[i];while(x&&__gcd(a[i],a[x])==1)x=p[x];an[i]=x?x:-1;}for(int i=1;i<=n;i++){int x=p[i];while(x&&__gcd(a[i],a[x])==1)x=p[x];if(an[i]!=(x?x:-1))return cout<<"WA\n",1;}}cout<<"OK\n";}
'''
add('P2441','P2441 角色属性树',r'''把属性分解成不重复质因子。固定所有属性时，DFS 过程中维护每个质因子在当前根链上最后出现的节点；一个节点的答案就是其各质因子对应节点中深度最大的一个，退出子树时恢复现场。

修改最多 $50$ 次，因此每次修改后重新做一遍 $O(n\log a)$ 的树上扫描即可。操作先离线读入，将所有出现过的质因子离散化，维护表均用静态数组。''',{'.cpp':C,' 数据生成.cpp':CG,' 暴力.cpp':CB,' 对拍.cpp':CS},parts=[CB],extra=[('3 3\n2 3 6\n1 2\n2 3\n1 3\n2 2 2\n1 3\n','2\n2\n'),('2 2\n5 7\n1 2\n1 2\n2 1 14\n','-1\n'),('1 3\n2147483647\n1 1\n2 1 6\n1 1\n','-1\n-1\n')])

D=r'''#include <bits/stdc++.h>
using namespace std;using u=unsigned long long;using U=__uint128_t;u p(u a,u b,u m){u r=1;for(;b;b>>=1,a=(U)a*a%m)if(b&1)r=(U)r*a%m;return r;}bool q(u n){if(n<2)return 0;for(u x:{2,3,5,7,11,13,17,19,23,29,31,37}){if(n%x==0)return n==x;}u d=n-1,s=0;while(!(d&1))d>>=1,s++;for(u a:{2,325,9375,28178,450775,9780504,1795265022})if(a%n){u x=p(a%n,d,n);if(x==1||x==n-1)continue;bool f=0;for(u i=1;i<s;i++)if((x=(U)x*x%n)==n-1){f=1;break;}if(!f)return 0;}return 1;}int main(){ios::sync_with_stdio(0);cin.tie(0);u n,k;cin>>n>>k;u x=k+1;cout<<(q(x)&&2*x>n+1?1:2)<<'\n';}
'''
DB=r'''#include <bits/stdc++.h>
using namespace std;const int N=1005;int d[N],q[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n,k,l=0,r=0;cin>>n>>k;memset(d,-1,sizeof d);d[k-1]=0;q[r++]=k-1;while(l<r){int x=q[l++];for(int y=0;y<n;y++)if(d[y]<0&&__gcd(x+2,y+2)==1)d[y]=d[x]+1,q[r++]=y;}cout<<*max_element(d,d+n)<<'\n';}
'''
DG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000000000000ULL;mt19937_64 g(s);unsigned long long n=g()%min(100000000000000ULL,max(2ULL,z)-1)+2;cout<<n<<' '<<g()%n+1<<'\n';}
'''
DS=r'''#include <bits/stdc++.h>
using namespace std;bool q(long long n){if(n<2)return 0;for(long long i=2;i*i<=n;i++)if(n%i==0)return 0;return 1;}int main(int C,char**v){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(v[1]):1000;unsigned long long s=C>2?stoull(v[2]):1;mt19937_64 g(s);while(R--){int n=g()%500+2,k=g()%n+1,x=k+1,a=q(x)&&2*x>n+1?1:2,b=0;for(int y=2;y<=n+1;y++)if(y!=x&&__gcd(x,y)>1)b=2;if(!b)b=1;if(a!=b)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P5535','P5535 【XR-3】小道消息',r'''传播图的直径不超过二，所以答案只可能是 $1$ 或 $2$。设起点衣服上的数为 $x=k+1$。一天内传遍等价于区间 $[2,n+1]$ 中除 $x$ 外的数都与 $x$ 互质。

若 $x$ 合数，它的真质因子已经构成反例；若 $x$ 是质数，唯一可能的反例从 $2x$ 开始。因此仅当 $x$ 为质数且 $2x>n+1$ 时答案为 $1$，否则为 $2$。''',{'.cpp':D,' 数据生成.cpp':DG,' 暴力.cpp':DB,' 对拍.cpp':DS},extra=[('2 1\n','1\n'),('4 1\n','2\n'),('10 6\n','1\n'),('10 5\n','2\n')])
