from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const long long P=1e9;const int N=85;long long a[N][N];int id[10][10];char s[10][10];int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m,k=0;cin>>n>>m;for(int i=0;i<n;i++){cin>>s[i];for(int j=0;j<m;j++)if(s[i][j]=='.')id[i][j]=k++;else id[i][j]=-1;}if(k<2)return cout<<k<<'\n',0;for(int i=0;i<n;i++)for(int j=0;j<m;j++)if(id[i][j]>=0){if(i+1<n&&id[i+1][j]>=0){int x=id[i][j],y=id[i+1][j];a[x][x]++;a[y][y]++;a[x][y]=a[y][x]=P-1;}if(j+1<m&&id[i][j+1]>=0){int x=id[i][j],y=id[i][j+1];a[x][x]++;a[y][y]++;a[x][y]=a[y][x]=P-1;}}k--;long long z=1;for(int i=0;i<k;i++)for(int j=i+1;j<k;j++)while(a[j][i]){long long q=a[i][i]/a[j][i];for(int x=i;x<k;x++)a[i][x]=(a[i][x]-q*a[j][x]%P+P)%P;for(int x=i;x<k;x++)swap(a[i][x],a[j][x]);z=P-z;}for(int i=0;i<k;i++)z=z*a[i][i]%P;cout<<z<<'\n';}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=85;int id[10][10],u[145],v[145],f[N];char s[10][10];int g(int x){return f[x]==x?x:f[x]=g(f[x]);}int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m,k=0,e=0;cin>>n>>m;for(int i=0;i<n;i++){cin>>s[i];for(int j=0;j<m;j++)if(s[i][j]=='.')id[i][j]=k++;else id[i][j]=-1;}for(int i=0;i<n;i++)for(int j=0;j<m;j++)if(id[i][j]>=0){if(i+1<n&&id[i+1][j]>=0)u[e]=id[i][j],v[e++]=id[i+1][j];if(j+1<m&&id[i][j+1]>=0)u[e]=id[i][j],v[e++]=id[i][j+1];}long long r=0;for(int q=0;q<(1<<e);q++)if(__builtin_popcount(q)==k-1){for(int i=0;i<k;i++)f[i]=i;bool z=1;for(int i=0;i<e;i++)if(q>>i&1){int x=g(u[i]),y=g(v[i]);if(x==y){z=0;break;}f[x]=y;}r+=z;}cout<<r%1000000000<<'\n';}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):5;mt19937_64 g(s);int n=g()%min(9ULL,max(1ULL,z))+1,m=g()%min(9ULL,max(1ULL,z))+1;cout<<n<<' '<<m<<'\n';for(int i=0;i<n;i++){for(int j=0;j<m;j++)cout<<(!i&&!j||g()%4?'.':'*');cout<<'\n';}}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const long long P=1e9;long long a[10][10];int u[15],v[15],f[10];int g(int x){return f[x]==x?x:f[x]=g(f[x]);}long long d(int n){if(n==1)return 1;int k=n-1;long long z=1;for(int i=0;i<k;i++)for(int j=i+1;j<k;j++)while(a[j][i]){long long q=a[i][i]/a[j][i];for(int x=i;x<k;x++)a[i][x]=(a[i][x]-q*a[j][x]%P+P)%P;for(int x=i;x<k;x++)swap(a[i][x],a[j][x]);z=P-z;}for(int i=0;i<k;i++)z=z*a[i][i]%P;return z;}int main(int c,char**v0){ios::sync_with_stdio(0);cin.tie(0);int R=c>1?stoi(v0[1]):1000;unsigned long long s=c>2?stoull(v0[2]):1;mt19937_64 h(s);while(R--){int n=h()%6+1,e=0;memset(a,0,sizeof a);for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(h()%3==0){u[e]=i;v[e++]=j;a[i][i]++;a[j][j]++;a[i][j]=a[j][i]=P-1;}long long x=0;for(int q=0;q<(1<<e);q++)if(__builtin_popcount(q)==n-1){for(int i=0;i<n;i++)f[i]=i;bool z=1;for(int i=0;i<e;i++)if(q>>i&1){int p=g(u[i]),r=g(v[i]);if(p==r){z=0;break;}f[p]=r;}x+=z;}if(d(n)!=x%P)return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P4111','P4111 [HEOI2015] 小 Z 的房间','合法拆墙集合必须连通且无环，正好是房间邻接图的生成树。构造拉普拉斯矩阵，删除任意一行一列后求行列式。模数不是质数，因此用只含整行倍减与交换的欧几里得消元。',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},parts=[AB],extra=[('1 1\n.\n','1\n'),('1 2\n..\n','1\n'),('1 3\n.*.\n','0\n')])
