import re
from build_lib import q,w

def add(p,b,e,sol,codes,parts=(),extra=()):
 x=q(p);z=x['contenu'];g=lambda y,k:y.get(k,'').strip()
 s=f"# {p} {z['name']}\n\n## 中文题面\n\n### 题目描述\n\n{g(z,'description')}\n\n### 输入格式\n\n{g(z,'formatI')}\n\n### 输出格式\n\n{g(z,'formatO')}"
 for i,a in enumerate(x.get('samples',[]),1):s+=f"\n\n### 样例 {i}\n\n```text\n{a[0].rstrip()}\n```\n\n```text\n{a[1].rstrip()}\n```"
 s+=f"\n\n### 说明与限制\n\n{g(z,'hint')}\n\n## English Statement\n\n### Description\n\n{e[0]}\n\n### Input\n\n{e[1]}\n\n### Output\n\n{e[2]}\n\n### Constraints\n\n{e[3]}"
 w(b+'.md',s);w(b+' 题解.md',f'# {b} 题解\n\n{sol}')
 for k,v in codes.items():w(b+k,v)
 for i,v in enumerate(parts,1):w(f'{b} 部分分{i}.cpp',v)
 d='cph/'+b;k=0
 for k,a in enumerate(x.get('samples',[]),1):w(f'{d}/{b}_{k}.in',a[0]);w(f'{d}/{b}_{k}.ans',a[1])
 for a,o in extra:k+=1;w(f'{d}/{b}_{k}.in',a);w(f'{d}/{b}_{k}.ans',o)

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=262144,P=998244353,G=3,M=64005,S=1500000;static int a[N],b[N],c[N],d[N],r[N],v[N],t[S],y[S],u[4*M],z[4*M],x[M],o[M];static int n,m,e,k;
int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}
void f(int*a,int n,int q){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=pw(G,(P-1)/l);if(q<0)w=pw(w);for(int i=0;i<n;i+=l)for(int j=0,s=1;j<l/2;j++,s=1LL*s*w%P){int x=a[i+j],y=1LL*s*a[i+j+l/2]%P;a[i+j]=(x+y)%P;a[i+j+l/2]=(x-y+P)%P;}}if(q<0){int w=pw(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}
void ml(const int*x,int n,const int*y,int m,int*o){int l=n+m-1;if(1LL*n*m<=256){memset(o,0,l*sizeof(int));for(int i=0;i<n;i++)for(int j=0;j<m;j++)o[i+j]=(o[i+j]+1LL*x[i]*y[j])%P;return;}int q=1,s=0;while(q<l)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,n*sizeof(int));memcpy(b,y,m*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)a[i]=1LL*a[i]*b[i]%P;f(a,q,-1);memcpy(o,a,l*sizeof(int));}
void iv(const int*x,int n,int*y){memset(y,0,n*sizeof(int));y[0]=pw(x[0]);for(int k=1;k<n;k<<=1){int l=min(k<<1,n),q=1,s=0;while(q<l*2)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,l*sizeof(int));memcpy(b,y,k*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)b[i]=1LL*b[i]*(2-1LL*a[i]*b[i]%P+P)%P;f(b,q,-1);memcpy(y+k,b+k,(l-k)*sizeof(int));}}
void md(const int*x,int n,const int*g,int m,int*o){if(n<m){memcpy(o,x,n*sizeof(int));memset(o+n,0,(m-1-n)*sizeof(int));return;}if(m<=32){memcpy(c,x,n*sizeof(int));int w=pw(g[m-1]);for(int i=n-1;i>=m-1;i--){int s=1LL*c[i]*w%P;for(int j=0;j<m;j++)c[i-m+1+j]=(c[i-m+1+j]-1LL*s*g[j]%P+P)%P;}memcpy(o,c,(m-1)*sizeof(int));return;}int q=n-m+1;memset(c,0,q*sizeof(int));for(int i=0;i<m&&i<q;i++)c[i]=g[m-1-i];iv(c,q,d);for(int i=0;i<q;i++)v[i]=x[n-1-i];ml(v,q,d,q,c);for(int i=0;i<q;i++)v[i]=c[q-1-i];ml(g,m,v,q,c);for(int i=0;i<m-1;i++)o[i]=(x[i]-c[i]+P)%P;}
void bd(int q,int l,int h){if(l==h){u[q]=e;z[q]=2;t[e++]=(P-x[l])%P;t[e++]=1;return;}int m=(l+h)>>1;bd(q<<1,l,m);bd(q<<1|1,m+1,h);u[q]=e;z[q]=z[q<<1]+z[q<<1|1]-1;ml(t+u[q<<1],z[q<<1],t+u[q<<1|1],z[q<<1|1],t+e);e+=z[q];}
void ev(int q,int l,int h,const int*p,int n){if(l==h){o[l]=n?p[0]:0;return;}int m=(l+h)>>1,L=z[q<<1]-1,R=z[q<<1|1]-1,s=k;k+=L;md(p,n,t+u[q<<1],z[q<<1],y+s);int h0=k;k+=R;md(p,n,t+u[q<<1|1],z[q<<1|1],y+h0);ev(q<<1,l,m,y+s,L);ev(q<<1|1,m+1,h,y+h0,R);}
int main(){ios::sync_with_stdio(0);cin.tie(0);cin>>n>>m;for(int i=0;i<=n;i++)cin>>v[i];for(int i=0;i<m;i++)cin>>x[i];bd(1,0,m-1);k=0;if(n+1>=z[1]){k=m;md(v,n+1,t+u[1],z[1],y);ev(1,0,m-1,y,m);}else ev(1,0,m-1,v,n+1);for(int i=0;i<m;i++)cout<<o[i]<<'\n';}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=64005,P=998244353;static int a[N],x[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n,m;cin>>n>>m;for(int i=0;i<=n;i++)cin>>a[i];for(int i=0;i<m;i++)cin>>x[i];for(int i=0;i<m;i++){int s=0;for(int j=n;j>=0;j--)s=(1LL*s*x[i]+a[j])%P;cout<<s<<'\n';}}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;const int P=998244353;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):64000;z=min(64000ULL,max(1ULL,z));mt19937_64 g(s);int n=g()%z+1,m=g()%z+1;cout<<n<<' '<<m<<'\n';for(int i=0;i<=n;i++)cout<<g()%P<<' ';cout<<'\n';for(int i=0;i<m;i++)cout<<g()%P<<' ';cout<<'\n';}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const int N=512,P=998244353,G=3,M=128,S=4096;static int a[N],b[N],c[N],d[N],r[N],v[N],t[S],y[S],u[4*M],z[4*M],x[M],o[M],w[M];static int e,k;
int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int q){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=pw(G,(P-1)/l);if(q<0)w=pw(w);for(int i=0;i<n;i+=l)for(int j=0,s=1;j<l/2;j++,s=1LL*s*w%P){int x=a[i+j],y=1LL*s*a[i+j+l/2]%P;a[i+j]=(x+y)%P;a[i+j+l/2]=(x-y+P)%P;}}if(q<0){int w=pw(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void ml(const int*x,int n,const int*y,int m,int*o){int l=n+m-1;if(1LL*n*m<=64){memset(o,0,l*sizeof(int));for(int i=0;i<n;i++)for(int j=0;j<m;j++)o[i+j]=(o[i+j]+1LL*x[i]*y[j])%P;return;}int q=1,s=0;while(q<l)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,n*sizeof(int));memcpy(b,y,m*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)a[i]=1LL*a[i]*b[i]%P;f(a,q,-1);memcpy(o,a,l*sizeof(int));}void iv(const int*x,int n,int*y){memset(y,0,n*sizeof(int));y[0]=pw(x[0]);for(int k=1;k<n;k<<=1){int l=min(k<<1,n),q=1,s=0;while(q<l*2)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,l*sizeof(int));memcpy(b,y,k*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)b[i]=1LL*b[i]*(2-1LL*a[i]*b[i]%P+P)%P;f(b,q,-1);memcpy(y+k,b+k,(l-k)*sizeof(int));}}void md(const int*x,int n,const int*g,int m,int*o){if(n<m){memcpy(o,x,n*sizeof(int));memset(o+n,0,(m-1-n)*sizeof(int));return;}if(m<=8){memcpy(c,x,n*sizeof(int));for(int i=n-1;i>=m-1;i--)for(int j=0,s=c[i];j<m;j++)c[i-m+1+j]=(c[i-m+1+j]-1LL*s*g[j]%P+P)%P;memcpy(o,c,(m-1)*sizeof(int));return;}int q=n-m+1;memset(c,0,q*sizeof(int));for(int i=0;i<m&&i<q;i++)c[i]=g[m-1-i];iv(c,q,d);for(int i=0;i<q;i++)v[i]=x[n-1-i];ml(v,q,d,q,c);for(int i=0;i<q;i++)v[i]=c[q-1-i];ml(g,m,v,q,c);for(int i=0;i<m-1;i++)o[i]=(x[i]-c[i]+P)%P;}void bd(int q,int l,int h){if(l==h){u[q]=e;z[q]=2;t[e++]=(P-x[l])%P;t[e++]=1;return;}int m=(l+h)>>1;bd(q<<1,l,m);bd(q<<1|1,m+1,h);u[q]=e;z[q]=z[q<<1]+z[q<<1|1]-1;ml(t+u[q<<1],z[q<<1],t+u[q<<1|1],z[q<<1|1],t+e);e+=z[q];}void ev(int q,int l,int h,const int*p,int n){if(l==h){o[l]=p[0];return;}int m=(l+h)>>1,L=z[q<<1]-1,R=z[q<<1|1]-1,s=k;k+=L;md(p,n,t+u[q<<1],z[q<<1],y+s);int h0=k;k+=R;md(p,n,t+u[q<<1|1],z[q<<1|1],y+h0);ev(q<<1,l,m,y+s,L);ev(q<<1|1,m+1,h,y+h0,R);}int main(int C,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(V[1]):1000;unsigned long long s=C>2?stoull(V[2]):1;mt19937_64 g(s);while(R--){int n=g()%60+1,m=g()%60+1;e=k=0;for(int i=0;i<=n;i++)v[i]=g()%P;for(int i=0;i<m;i++)x[i]=g()%P;bd(1,0,m-1);if(n+1>=z[1]){k=m;md(v,n+1,t+u[1],z[1],y);ev(1,0,m-1,y,m);}else ev(1,0,m-1,v,n+1);for(int i=0;i<m;i++){int q=0;for(int j=n;j>=0;j--)q=(1LL*q*x[i]+v[j])%P;if(q!=o[i])return cout<<"WA\n",1;}}cout<<"OK\n";}
'''
def mdbuf(s):
 s=s.replace('r[N],v[N]','r[N],j[N],v[N]')
 a,b=s.split('void md',1);b,c=re.split(r'}\s*void bd',b,maxsplit=1)
 b=re.sub(r'\bv\b','j',b)
 return a+'void md'+b+'}\nvoid bd'+c
A=mdbuf(A);AS=mdbuf(AS)
add('P5050','P5050 【模板】多项式多点求值',('Given a polynomial $f(x)$ of degree $n$, compute $f(a_i)$ for every $i\\in[1,m]$.','The first line contains $n,m$. The second line contains the $n+1$ coefficients of $f$ in increasing order of degree. The third line contains the $m$ evaluation points $a_i$.','Print $m$ lines. Line $i$ contains $f(a_i)\\bmod 998244353$.','$1\\le n,m\\le64000$. Every coefficient and evaluation point is in $[0,998244353)$.') ,r'''Build the product tree whose leaf for point $a_i$ is $x-a_i$. Reduce $f$ modulo the polynomial at the root, then recursively reduce each remainder modulo the two child polynomials. At a leaf the constant remainder is exactly the requested value.

Polynomial multiplication and the reversed-polynomial division formula are implemented with NTT. The product tree has $O((n+m)\log m)$ stored coefficients. The total time is $O((n+m)\log^2(n+m))$ and the space usage is $O((n+m)\log m)$.''',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},parts=[AB],extra=[('1 1\n0 0\n0\n','0\n'),('2 3\n1 2 3\n0 1 2\n','1\n6\n17\n'),('3 2\n998244352 1 0 1\n998244352 1\n','998244350\n1\n'),('1 3\n5 7\n3 3 0\n','26\n26\n5\n')])

B=r'''#include <bits/stdc++.h>
using namespace std;const int N=524288,P=998244353,G=3,M=100005,S=2100000;static int a[N],b[N],c[N],d[N],r[N],v[N],t[S],y[S],u[4*M],z[4*M],x[M],h[M],o[M];static int n,e,k;
int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int q){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=pw(G,(P-1)/l);if(q<0)w=pw(w);for(int i=0;i<n;i+=l)for(int j=0,s=1;j<l/2;j++,s=1LL*s*w%P){int x=a[i+j],y=1LL*s*a[i+j+l/2]%P;a[i+j]=(x+y)%P;a[i+j+l/2]=(x-y+P)%P;}}if(q<0){int w=pw(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void ml(const int*x,int n,const int*y,int m,int*o){int l=n+m-1;if(1LL*n*m<=256){memset(o,0,l*sizeof(int));for(int i=0;i<n;i++)for(int j=0;j<m;j++)o[i+j]=(o[i+j]+1LL*x[i]*y[j])%P;return;}int q=1,s=0;while(q<l)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,n*sizeof(int));memcpy(b,y,m*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)a[i]=1LL*a[i]*b[i]%P;f(a,q,-1);memcpy(o,a,l*sizeof(int));}void iv(const int*x,int n,int*y){memset(y,0,n*sizeof(int));y[0]=pw(x[0]);for(int k=1;k<n;k<<=1){int l=min(k<<1,n),q=1,s=0;while(q<l*2)q<<=1,s++;memset(a,0,q*sizeof(int));memset(b,0,q*sizeof(int));memcpy(a,x,l*sizeof(int));memcpy(b,y,k*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(a,q,1);f(b,q,1);for(int i=0;i<q;i++)b[i]=1LL*b[i]*(2-1LL*a[i]*b[i]%P+P)%P;f(b,q,-1);memcpy(y+k,b+k,(l-k)*sizeof(int));}}void md(const int*x,int n,const int*g,int m,int*o){if(n<m){memcpy(o,x,n*sizeof(int));memset(o+n,0,(m-1-n)*sizeof(int));return;}if(m<=32){memcpy(c,x,n*sizeof(int));int w=pw(g[m-1]);for(int i=n-1;i>=m-1;i--){int s=1LL*c[i]*w%P;for(int j=0;j<m;j++)c[i-m+1+j]=(c[i-m+1+j]-1LL*s*g[j]%P+P)%P;}memcpy(o,c,(m-1)*sizeof(int));return;}int q=n-m+1;memset(c,0,q*sizeof(int));for(int i=0;i<m&&i<q;i++)c[i]=g[m-1-i];iv(c,q,d);for(int i=0;i<q;i++)v[i]=x[n-1-i];ml(v,q,d,q,c);for(int i=0;i<q;i++)v[i]=c[q-1-i];ml(g,m,v,q,c);for(int i=0;i<m-1;i++)o[i]=(x[i]-c[i]+P)%P;}void bd(int q,int l,int h0){if(l==h0){u[q]=e;z[q]=2;t[e++]=(P-x[l])%P;t[e++]=1;return;}int m=(l+h0)>>1;bd(q<<1,l,m);bd(q<<1|1,m+1,h0);u[q]=e;z[q]=z[q<<1]+z[q<<1|1]-1;ml(t+u[q<<1],z[q<<1],t+u[q<<1|1],z[q<<1|1],t+e);e+=z[q];}void ev(int q,int l,int h0,const int*p,int n){if(l==h0){h[l]=p[0];return;}int m=(l+h0)>>1,L=z[q<<1]-1,R=z[q<<1|1]-1,s=k;k+=L;md(p,n,t+u[q<<1],z[q<<1],y+s);int j=k;k+=R;md(p,n,t+u[q<<1|1],z[q<<1|1],y+j);ev(q<<1,l,m,y+s,L);ev(q<<1|1,m+1,h0,y+j,R);}int ip(int q,int l,int h0){if(l==h0){int s=e++;y[s]=1LL*o[l]*pw(h[l])%P;return s;}int m=(l+h0)>>1,L=ip(q<<1,l,m),R=ip(q<<1|1,m+1,h0),p=e;e+=h0-l+1;ml(y+L,m-l+1,t+u[q<<1|1],z[q<<1|1],c);memcpy(y+p,c,(h0-l+1)*sizeof(int));ml(y+R,h0-m,t+u[q<<1],z[q<<1],c);for(int i=0;i<=h0-l;i++)y[p+i]=(y[p+i]+c[i])%P;return p;}int main(){ios::sync_with_stdio(0);cin.tie(0);cin>>n;for(int i=0;i<n;i++)cin>>x[i]>>o[i];bd(1,0,n-1);for(int i=1;i<=n;i++)v[i-1]=1LL*i*t[u[1]+i]%P;k=0;ev(1,0,n-1,v,n);e=0;int s=ip(1,0,n-1);for(int i=0;i<n;i++)cout<<y[s+i]<<' ';cout<<'\n';}
'''
B=mdbuf(B)
BB=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005,P=998244353;static int x[N],a[N],c[N];int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>x[i]>>c[i];for(int l=1;l<n;l++)for(int i=n-1;i>=l;i--)c[i]=1LL*(c[i]-c[i-1]+P)*pw((x[i]-x[i-l]+P)%P)%P;a[0]=c[n-1];int m=1;for(int i=n-2;i>=0;i--){for(int j=m;j;j--)a[j]=(a[j-1]-1LL*x[i]*a[j]%P+P)%P;a[0]=(c[i]-1LL*x[i]*a[0]%P+P)%P;m++;}for(int i=0;i<n;i++)cout<<a[i]<<' ';cout<<'\n';}
'''
BG=r'''#include <bits/stdc++.h>
using namespace std;const int P=998244353;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;z=min(100000ULL,max(1ULL,z));mt19937_64 g(s);int n=g()%z+1,a=g()%P,d=g()%(P-1)+1;cout<<n<<'\n';for(int i=0;i<n;i++)cout<<(a+1LL*i*d)%P<<' '<<g()%P<<'\n';}
'''
BS=r'''#include <bits/stdc++.h>
using namespace std;const int N=128,P=998244353;static int x[N],y[N],a[N],b[N],c[N],d[N];int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}int main(int C,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(V[1]):1000;unsigned long long s=C>2?stoull(V[2]):1;mt19937_64 g(s);while(R--){int n=g()%70+1,q=g()%P,z=g()%(P-1)+1;memset(a,0,sizeof a);for(int i=0;i<n;i++)x[i]=(q+1LL*i*z)%P,y[i]=g()%P,c[i]=y[i];for(int l=1;l<n;l++)for(int i=n-1;i>=l;i--)c[i]=1LL*(c[i]-c[i-1]+P)*pw((x[i]-x[i-l]+P)%P)%P;a[0]=c[n-1];int m=1;for(int i=n-2;i>=0;i--){for(int j=m;j;j--)a[j]=(a[j-1]-1LL*x[i]*a[j]%P+P)%P;a[0]=(c[i]-1LL*x[i]*a[0]%P+P)%P;m++;}for(int i=0;i<n;i++){int w=0;for(int j=n-1;j>=0;j--)w=(1LL*w*x[i]+a[j])%P;if(w!=y[i])return cout<<"WA\n",1;}for(int i=0;i<n;i++)b[i]=g()%P;for(int i=0;i<n;i++){int w=0;for(int j=n-1;j>=0;j--)w=(1LL*w*x[i]+b[j])%P;d[i]=w;}memcpy(c,d,n*sizeof(int));for(int l=1;l<n;l++)for(int i=n-1;i>=l;i--)c[i]=1LL*(c[i]-c[i-1]+P)*pw((x[i]-x[i-l]+P)%P)%P;memset(a,0,sizeof a);a[0]=c[n-1];m=1;for(int i=n-2;i>=0;i--){for(int j=m;j;j--)a[j]=(a[j-1]-1LL*x[i]*a[j]%P+P)%P;a[0]=(c[i]-1LL*x[i]*a[0]%P+P)%P;m++;}for(int i=0;i<n;i++)if(a[i]!=b[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
BS=B.split('int main()',1)[0]+r'''static int p[M],q[M];int main(int C,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(V[1]):1000;unsigned long long s=C>2?stoull(V[2]):1;mt19937_64 g(s);while(R--){n=g()%60+1;int w=g()%P,l=g()%(P-1)+1;e=k=0;for(int i=0;i<n;i++)x[i]=(w+1LL*i*l)%P,o[i]=g()%P;bd(1,0,n-1);for(int i=1;i<=n;i++)v[i-1]=1LL*i*t[u[1]+i]%P;ev(1,0,n-1,v,n);e=0;int z0=ip(1,0,n-1);for(int i=0;i<n;i++)p[i]=o[i];for(int z1=1;z1<n;z1++)for(int i=n-1;i>=z1;i--)p[i]=1LL*(p[i]-p[i-1]+P)*pw((x[i]-x[i-z1]+P)%P)%P;memset(q,0,n*sizeof(int));q[0]=p[n-1];int m=1;for(int i=n-2;i>=0;i--){for(int j=m;j;j--)q[j]=(q[j-1]-1LL*x[i]*q[j]%P+P)%P;q[0]=(p[i]-1LL*x[i]*q[0]%P+P)%P;m++;}for(int i=0;i<n;i++)if(y[z0+i]!=q[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P5158','P5158 【模板】多项式快速插值',('Given $n$ points $(x_i,y_i)$ with distinct $x_i$, find the unique polynomial $f$ of degree less than $n$ such that $f(x_i)\\equiv y_i\\pmod{998244353}$.','The first line contains $n$. Each of the next $n$ lines contains $x_i,y_i$.','Print the $n$ coefficients of $f$ in increasing order of degree. Pad with zeroes when its degree is less than $n-1$.','$1\\le n\\le100000$, $0\\le x_i,y_i<998244353$, and all $x_i$ are distinct.'),r'''Let $M(x)=\prod_i(x-x_i)$. Build all subproducts with a product tree, differentiate the root polynomial, and evaluate $M'(x)$ at all $x_i$ with the multipoint-evaluation algorithm. The Lagrange weight at leaf $i$ is

$$w_i=\frac{y_i}{M'(x_i)}.$$

When merging two tree nodes, combine their interpolation polynomials as $F=F_LM_R+F_RM_L$. NTT performs every multiplication. The time complexity is $O(n\log^2 n)$ and the space complexity is $O(n\log n)$.''',{'.cpp':B,' 数据生成.cpp':BG,' 暴力.cpp':BB,' 对拍.cpp':BS},parts=[BB],extra=[('1\n5 7\n','7\n'),('2\n0 1\n1 3\n','1 2\n'),('3\n998244352 3\n0 2\n1 3\n','2 0 1\n'),('3\n2 25\n4 69\n7 180\n','5 4 3\n')])

C=r'''#include <bits/stdc++.h>
using namespace std;const int N=524288,P=998244353,G=3;static int a[N],b[N],c[N],d[N],e[N],h[N],r[N];int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int q){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=pw(G,(P-1)/l);if(q<0)w=pw(w);for(int i=0;i<n;i+=l)for(int j=0,s=1;j<l/2;j++,s=1LL*s*w%P){int x=a[i+j],y=1LL*s*a[i+j+l/2]%P;a[i+j]=(x+y)%P;a[i+j+l/2]=(x-y+P)%P;}}if(q<0){int w=pw(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void iv(const int*x,int n,int*y){memset(y,0,n*sizeof(int));y[0]=pw(x[0]);for(int k=1;k<n;k<<=1){int l=min(k<<1,n),q=1,s=0;while(q<l*2)q<<=1,s++;memset(e,0,q*sizeof(int));memset(h,0,q*sizeof(int));memcpy(e,x,l*sizeof(int));memcpy(h,y,k*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(e,q,1);f(h,q,1);for(int i=0;i<q;i++)h[i]=1LL*h[i]*(2-1LL*e[i]*h[i]%P+P)%P;f(h,q,-1);memcpy(y+k,h+k,(l-k)*sizeof(int));}}void cv(const int*x,int n,const int*y,int m,int*o,int z){int q=1,s=0;while(q<n+m-1)q<<=1,s++;memset(c,0,q*sizeof(int));memset(d,0,q*sizeof(int));memcpy(c,x,n*sizeof(int));memcpy(d,y,m*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(c,q,1);f(d,q,1);for(int i=0;i<q;i++)c[i]=1LL*c[i]*d[i]%P;f(c,q,-1);memcpy(o,c,z*sizeof(int));}int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];b[0]=1;for(int k=1;k<n;k<<=1){int l=min(k<<1,n);iv(b,l,c);cv(a,l,c,l,d,l);for(int i=0;i<l;i++)b[i]=1LL*(b[i]+d[i])*(P+1)/2%P;}for(int i=0;i<n;i++)cout<<b[i]<<' ';cout<<'\n';}
'''
def cvbuf(s):
 a,b=s.split('void cv',1);b,c=b.split('}int main',1)
 b=re.sub(r'\bc\b','e',b);b=re.sub(r'\bd\b','h',b)
 return a+'void cv'+b+'}int main'+c
C=cvbuf(C)
CB=r'''#include <bits/stdc++.h>
using namespace std;const int N=100005,P=998244353;static int a[N],b[N];int main(){ios::sync_with_stdio(0);cin.tie(0);int n;cin>>n;for(int i=0;i<n;i++)cin>>a[i];b[0]=1;for(int i=1;i<n;i++){long long s=0;for(int j=1;j<i;j++)s=(s+1LL*b[j]*b[i-j])%P;b[i]=1LL*(a[i]-s+P)*(P+1)/2%P;}for(int i=0;i<n;i++)cout<<b[i]<<' ';cout<<'\n';}
'''
CG=r'''#include <bits/stdc++.h>
using namespace std;const int P=998244353;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;z=min(100000ULL,max(1ULL,z));mt19937_64 g(s);int n=g()%z+1;cout<<n<<'\n'<<1<<' ';for(int i=1;i<n;i++)cout<<g()%P<<' ';cout<<'\n';}
'''
CS=r'''#include <bits/stdc++.h>
using namespace std;const int N=512,P=998244353,G=3;static int a[N],b[N],c[N],d[N],e[N],h[N],r[N],o[N];int pw(int a,int b=P-2){int s=1;for(;b;b>>=1,a=1LL*a*a%P)if(b&1)s=1LL*s*a%P;return s;}void f(int*a,int n,int q){for(int i=0;i<n;i++)if(i<r[i])swap(a[i],a[r[i]]);for(int l=2;l<=n;l<<=1){int w=pw(G,(P-1)/l);if(q<0)w=pw(w);for(int i=0;i<n;i+=l)for(int j=0,s=1;j<l/2;j++,s=1LL*s*w%P){int x=a[i+j],y=1LL*s*a[i+j+l/2]%P;a[i+j]=(x+y)%P;a[i+j+l/2]=(x-y+P)%P;}}if(q<0){int w=pw(n);for(int i=0;i<n;i++)a[i]=1LL*a[i]*w%P;}}void iv(const int*x,int n,int*y){memset(y,0,n*sizeof(int));y[0]=pw(x[0]);for(int k=1;k<n;k<<=1){int l=min(k<<1,n),q=1,s=0;while(q<l*2)q<<=1,s++;memset(e,0,q*sizeof(int));memset(h,0,q*sizeof(int));memcpy(e,x,l*sizeof(int));memcpy(h,y,k*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(e,q,1);f(h,q,1);for(int i=0;i<q;i++)h[i]=1LL*h[i]*(2-1LL*e[i]*h[i]%P+P)%P;f(h,q,-1);memcpy(y+k,h+k,(l-k)*sizeof(int));}}void cv(const int*x,int n,const int*y,int m,int*o,int z){int q=1,s=0;while(q<n+m-1)q<<=1,s++;memset(c,0,q*sizeof(int));memset(d,0,q*sizeof(int));memcpy(c,x,n*sizeof(int));memcpy(d,y,m*sizeof(int));r[0]=0;for(int i=1;i<q;i++)r[i]=(r[i>>1]>>1)|((i&1)<<(s-1));f(c,q,1);f(d,q,1);for(int i=0;i<q;i++)c[i]=1LL*c[i]*d[i]%P;f(c,q,-1);memcpy(o,c,z*sizeof(int));}int main(int C,char**V){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(V[1]):1000;unsigned long long s=C>2?stoull(V[2]):1;mt19937_64 g(s);while(R--){int n=g()%100+1;a[0]=1;for(int i=1;i<n;i++)a[i]=g()%P;memset(b,0,n*sizeof(int));b[0]=1;for(int k=1;k<n;k<<=1){int l=min(k<<1,n);iv(b,l,c);cv(a,l,c,l,d,l);for(int i=0;i<l;i++)b[i]=1LL*(b[i]+d[i])*(P+1)/2%P;}o[0]=1;for(int i=1;i<n;i++){long long q=0;for(int j=1;j<i;j++)q=(q+1LL*o[j]*o[i-j])%P;o[i]=1LL*(a[i]-q+P)*(P+1)/2%P;}for(int i=0;i<n;i++)if(b[i]!=o[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
CS=cvbuf(CS)
add('P5205','P5205 【模板】多项式开根',('Given a polynomial $A(x)$ of degree less than $n$, find $B(x)$ modulo $x^n$ such that $B(x)^2\\equiv A(x)\\pmod{x^n}$. If two answers exist, choose the one with the smaller constant coefficient. All coefficients are taken modulo $998244353$.','The first line contains $n$. The second line contains $a_0,a_1,\\ldots,a_{n-1}$. It is guaranteed that $a_0=1$.','Print the $n$ coefficients $b_0,b_1,\\ldots,b_{n-1}$.','$1\\le n\\le100000$ and $0\\le a_i<998244353$.'),r'''Since $a_0=1$, the required smaller constant coefficient is $b_0=1$. Suppose $B$ is correct modulo $x^k$. Newton iteration for the equation $B^2-A=0$ gives

$$B\leftarrow\frac{B+A/B}{2}\pmod{x^{2k}}.$$

Compute the polynomial inverse and products with NTT, doubling the known precision each round. The total time complexity is $O(n\log n)$ and the space complexity is $O(n)$.''',{'.cpp':C,' 数据生成.cpp':CG,' 暴力.cpp':CB,' 对拍.cpp':CS},parts=[CB],extra=[('1\n1\n','1\n'),('4\n1 2 1 0\n','1 1 0 0\n'),('5\n1 4 10 12 9\n','1 2 3 0 0\n')])
