from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=48;const long long P=1e9+7;long long a[32][N][N],f[N],g[N];int id(int m,int u,int p){return(m*3+u)*4+p;}void d(int r,int m,int u,int p,int o,int c,int s){if(r==2){a[0][s][id(o,u,c)]++;return;}if(m>>r&1){d(r+1,m,u,p,o,c,s);return;}if(!r&&!(m&2))d(2,m,u,p,o,c,s);d(r+1,m,u,p,o|1<<r,c,s);if(u<2&&!c&&!(p>>r&1))d(r+1,m,u+1,p,o,c|1<<r,s);}void init(){for(int m=0;m<4;m++)for(int u=0;u<3;u++)for(int p=0;p<4;p++)d(0,m,u,p,0,0,id(m,u,p));for(int z=1;z<32;z++)for(int i=0;i<N;i++)for(int k=0;k<N;k++)if(a[z-1][i][k])for(int j=0;j<N;j++)a[z][i][j]=(a[z][i][j]+a[z-1][i][k]*a[z-1][k][j])%P;}int main(){ios::sync_with_stdio(0);cin.tie(0);init();int t;cin>>t;while(t--){int n;cin>>n;memset(f,0,sizeof f);f[id(0,0,0)]=1;for(int z=0;n;n>>=1,z++)if(n&1){memset(g,0,sizeof g);for(int i=0;i<N;i++)for(int j=0;j<N;j++)g[j]=(g[j]+f[i]*a[z][i][j])%P;memcpy(f,g,sizeof g);}long long r=0;for(int p=0;p<4;p++)r=(r+f[id(0,2,p)])%P;cout<<r<<'\n';}}
'''
AB=r'''#include <bits/stdc++.h>
using namespace std;const int N=48;const long long P=1e9+7;long long a[N][N],f[N],g[N];int id(int m,int u,int p){return(m*3+u)*4+p;}void d(int r,int m,int u,int p,int o,int c,int s){if(r==2){a[s][id(o,u,c)]++;return;}if(m>>r&1){d(r+1,m,u,p,o,c,s);return;}if(!r&&!(m&2))d(2,m,u,p,o,c,s);d(r+1,m,u,p,o|1<<r,c,s);if(u<2&&!c&&!(p>>r&1))d(r+1,m,u+1,p,o,c|1<<r,s);}int main(){ios::sync_with_stdio(0);cin.tie(0);for(int m=0;m<4;m++)for(int u=0;u<3;u++)for(int p=0;p<4;p++)d(0,m,u,p,0,0,id(m,u,p));int t;cin>>t;while(t--){int n;cin>>n;memset(f,0,sizeof f);f[0]=1;while(n--){memset(g,0,sizeof g);for(int i=0;i<N;i++)for(int j=0;j<N;j++)g[j]=(g[j]+f[i]*a[i][j])%P;memcpy(f,g,sizeof g);}long long r=0;for(int p=0;p<4;p++)r=(r+f[id(0,2,p)])%P;cout<<r<<'\n';}}
'''
AG=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):20;mt19937_64 g(s);int t=min(500ULL,max(1ULL,z));cout<<t<<'\n';while(t--)cout<<g()%2000000000+1<<'\n';}
'''
AS=r'''#include <bits/stdc++.h>
using namespace std;const int N=48;const long long P=1e9+7;long long a[10][N][N],f[N],g[N],h[N];int id(int m,int u,int p){return(m*3+u)*4+p;}void d(int r,int m,int u,int p,int o,int c,int s){if(r==2){a[0][s][id(o,u,c)]++;return;}if(m>>r&1){d(r+1,m,u,p,o,c,s);return;}if(!r&&!(m&2))d(2,m,u,p,o,c,s);d(r+1,m,u,p,o|1<<r,c,s);if(u<2&&!c&&!(p>>r&1))d(r+1,m,u+1,p,o,c|1<<r,s);}int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);for(int m=0;m<4;m++)for(int u=0;u<3;u++)for(int p=0;p<4;p++)d(0,m,u,p,0,0,id(m,u,p));for(int z=1;z<10;z++)for(int i=0;i<N;i++)for(int k=0;k<N;k++)for(int j=0;j<N;j++)a[z][i][j]=(a[z][i][j]+a[z-1][i][k]*a[z-1][k][j])%P;int R=c>1?stoi(v[1]):1000;unsigned long long s=c>2?stoull(v[2]):1;mt19937_64 q(s);while(R--){int n=q()%100+1;memset(f,0,sizeof f);memset(h,0,sizeof h);f[0]=h[0]=1;for(int x=n,z=0;x;x>>=1,z++)if(x&1){memset(g,0,sizeof g);for(int i=0;i<N;i++)for(int j=0;j<N;j++)g[j]=(g[j]+f[i]*a[z][i][j])%P;memcpy(f,g,sizeof g);}for(int z=0;z<n;z++){memset(g,0,sizeof g);for(int i=0;i<N;i++)for(int j=0;j<N;j++)g[j]=(g[j]+h[i]*a[0][i][j])%P;memcpy(h,g,sizeof g);}for(int i=0;i<N;i++)if(f[i]!=h[i])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
add('P5303','P5303 [GXOI_GZOI2019] 逼死强迫症','按列轮廓 DP。状态记录下一列已被横砖占据的格子、已经放置的单格砖数、上一列单格砖位置；转移时同时排除横向和纵向相邻。状态数为 $48$，转移矩阵的幂可供所有询问共用。',{'.cpp':A,' 数据生成.cpp':AG,' 暴力.cpp':AB,' 对拍.cpp':AS},parts=[AB],extra=[('1\n3\n','2\n'),('1\n5\n','16\n'),('1\n10\n','554\n')])
