from build_lib import add

A=r'''#include <bits/stdc++.h>
using namespace std;const int N=100000;int p[N],h[N+5],e[3][N],n;bool v[N+5];long long P,M,r[3];long long z(long long x){x%=M;return x<0?x+M:x;}long long s(long long x){long long a=x,b=x+1;if(a&1)b/=2;else a/=2;return a%M*(b%M)%M;}long long E(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=a/t,B=b/t,C=c/t;x=(x+A)%M;y=(y+B)%M;u=(u+A%M*(B%M))%M;w=(w+A%M*(C%M))%M;if(t>L/q)break;t*=q;}return z(b%M*(c%M)%M*x+a%M*(c%M)%M*y-c%M*u-b%M*w);}long long F(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=t%M*s(a/t)%M,B=t%M*s(b/t)%M,C=t%M*s(c/t)%M;x=(x+A)%M;y=(y+B)%M;u=(u+A*B)%M;w=(w+A*C)%M;if(t>L/q)break;t*=q;}return z(s(b)*s(c)%M*x+s(a)*s(c)%M*y-s(c)*u-s(b)*w);}long long k(long long a,long long b){long long r=1;for(;b;b>>=1,a=a*a%P)if(b&1)r=r*a%P;return r;}int main(){ios::sync_with_stdio(0);cin.tie(0);h[1]=1;for(int i=2;i<=N;i++){if(!v[i])p[n++]=i,h[i]=i-1;for(int j=0;j<n&&i*p[j]<=N;j++){v[i*p[j]]=1;if(i%p[j]==0){h[i*p[j]]=h[i]*p[j];break;}h[i*p[j]]=h[i]*(p[j]-1);}}int T;cin>>T>>P;M=P-1;while(T--){int a,b,c;cin>>a>>b>>c;int L=max(a,b);for(int i=0;i<n&&p[i]<=L;i++)e[0][i]=E(p[i],a,b,c),e[1][i]=F(p[i],a,b,c),e[2][i]=0;for(int d=1;d<=min(a,min(b,c));d++){int x=a/d,y=b/d,z=c/d,l=max(x,y);for(int i=0;i<n&&p[i]<=l;i++)e[2][i]=(e[2][i]+h[d]%M*E(p[i],x,y,z))%M;}for(int j=0;j<3;j++)r[j]=1;for(int i=0;i<n&&p[i]<=L;i++)for(int j=0;j<3;j++)r[j]=r[j]*k(p[i],e[j][i])%P;cout<<r[0]<<' '<<r[1]<<' '<<r[2]<<'\n';}}
'''
B=r'''#include <bits/stdc++.h>
using namespace std;long long r[3],e[3];long long f(long long a,long long b,long long p){long long r=1;for(;b;b>>=1,a=a*a%p)if(b&1)r=r*a%p;return r;}int main(){ios::sync_with_stdio(0);cin.tie(0);int T;long long p;cin>>T>>p;while(T--){int A,B,C;cin>>A>>B>>C;for(int t=0;t<3;t++)r[t]=1;for(int i=1;i<=A;i++)for(int j=1;j<=B;j++)for(int k=1;k<=C;k++){long long x=1LL*i/__gcd(i,j)*j/__gcd(i,k);e[0]=1;e[1]=1LL*i*j*k;e[2]=__gcd(__gcd(i,j),k);for(int t=0;t<3;t++)r[t]=r[t]*f(x%p,e[t],p)%p;}cout<<r[0]<<' '<<r[1]<<' '<<r[2]<<'\n';}}
'''
C=r'''#include <bits/stdc++.h>
using namespace std;int main(int c,char**v){ios::sync_with_stdio(0);cin.tie(0);unsigned long long s=c>1?stoull(v[1]):1,z=c>2?stoull(v[2]):100000;mt19937_64 g(s);z=min(100000ULL,max(1ULL,z));cout<<70<<' '<<998244853<<'\n';for(int i=0;i<70;i++)cout<<g()%z+1<<' '<<g()%z+1<<' '<<g()%z+1<<'\n';}
'''
D=r'''#include <bits/stdc++.h>
using namespace std;const int N=11;int p[N],h[N],e[3][N],n;bool v[N];long long P=998244853,M=P-1,r[3],o[3],d[3];long long z(long long x){x%=M;return x<0?x+M:x;}long long s(long long x){long long a=x,b=x+1;if(a&1)b/=2;else a/=2;return a%M*(b%M)%M;}long long E(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=a/t,B=b/t,C=c/t;x=(x+A)%M;y=(y+B)%M;u=(u+A*B)%M;w=(w+A*C)%M;if(t>L/q)break;t*=q;}return z(b%M*(c%M)%M*x+a%M*(c%M)%M*y-c%M*u-b%M*w);}long long F(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=t%M*s(a/t)%M,B=t%M*s(b/t)%M,C=t%M*s(c/t)%M;x=(x+A)%M;y=(y+B)%M;u=(u+A*B)%M;w=(w+A*C)%M;if(t>L/q)break;t*=q;}return z(s(b)*s(c)%M*x+s(a)*s(c)%M*y-s(c)*u-s(b)*w);}long long k(long long a,long long b){long long r=1;for(;b;b>>=1,a=a*a%P)if(b&1)r=r*a%P;return r;}void q(int a,int b,int c,long long*f){int L=max(a,b);for(int i=0;i<n&&p[i]<=L;i++)e[0][i]=E(p[i],a,b,c),e[1][i]=F(p[i],a,b,c),e[2][i]=0;for(int d=1;d<=min(a,min(b,c));d++)for(int i=0;i<n&&p[i]<=max(a/d,b/d);i++)e[2][i]=(e[2][i]+h[d]*E(p[i],a/d,b/d,c/d))%M;for(int t=0;t<3;t++)f[t]=1;for(int i=0;i<n&&p[i]<=L;i++)for(int t=0;t<3;t++)f[t]=f[t]*k(p[i],e[t][i])%P;}int main(int C,char**w){ios::sync_with_stdio(0);cin.tie(0);int R=C>1?stoi(w[1]):1000;unsigned long long x=C>2?stoull(w[2]):1;mt19937_64 g(x);h[1]=1;for(int i=2;i<N;i++){if(!v[i])p[n++]=i,h[i]=i-1;for(int j=0;j<n&&i*p[j]<N;j++){v[i*p[j]]=1;if(i%p[j]==0){h[i*p[j]]=h[i]*p[j];break;}h[i*p[j]]=h[i]*(p[j]-1);}}while(R--){int a=g()%6+1,b=g()%6+1,c=g()%6+1;for(int t=0;t<3;t++)o[t]=1;q(a,b,c,r);for(int i=1;i<=a;i++)for(int j=1;j<=b;j++)for(int l=1;l<=c;l++){long long y=1LL*i/__gcd(i,j)*j/__gcd(i,l);d[0]=1;d[1]=1LL*i*j*l;d[2]=__gcd(__gcd(i,j),l);for(int t=0;t<3;t++)o[t]=o[t]*k(y,d[t])%P;}for(int t=0;t<3;t++)if(r[t]!=o[t])return cout<<"WA\n",1;}cout<<"OK\n";}
'''
P0=r'''#include <bits/stdc++.h>
using namespace std;const int N=100000;int p[N],n;bool v[N+5];long long P,M;long long z(long long x){x%=M;return x<0?x+M:x;}long long E(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=a/t,B=b/t,C=c/t;x=(x+A)%M;y=(y+B)%M;u=(u+A*B)%M;w=(w+A*C)%M;if(t>L/q)break;t*=q;}return z(b%M*(c%M)%M*x+a%M*(c%M)%M*y-c%M*u-b%M*w);}long long k(long long a,long long b){long long r=1;for(;b;b>>=1,a=a*a%P)if(b&1)r=r*a%P;return r;}int main(){ios::sync_with_stdio(0);cin.tie(0);for(int i=2;i<=N;i++){if(!v[i])p[n++]=i;for(int j=0;j<n&&i*p[j]<=N;j++){v[i*p[j]]=1;if(i%p[j]==0)break;}}int T;cin>>T>>P;M=P-1;while(T--){int a,b,c;cin>>a>>b>>c;long long r=1;for(int i=0;i<n&&p[i]<=max(a,b);i++)r=r*k(p[i],E(p[i],a,b,c))%P;cout<<r<<" 0 0\n";}}
'''
P1=r'''#include <bits/stdc++.h>
using namespace std;const int N=100000;int p[N],n;bool v[N+5];long long P,M;long long z(long long x){x%=M;return x<0?x+M:x;}long long s(long long x){long long a=x,b=x+1;if(a&1)b/=2;else a/=2;return a%M*(b%M)%M;}long long E(int q,int a,int b,int c){long long x=0,y=0,u=0,w=0,t=q,L=max(a,max(b,c));while(t<=L){long long A=t%M*s(a/t)%M,B=t%M*s(b/t)%M,C=t%M*s(c/t)%M;x=(x+A)%M;y=(y+B)%M;u=(u+A*B)%M;w=(w+A*C)%M;if(t>L/q)break;t*=q;}return z(s(b)*s(c)%M*x+s(a)*s(c)%M*y-s(c)*u-s(b)*w);}long long k(long long a,long long b){long long r=1;for(;b;b>>=1,a=a*a%P)if(b&1)r=r*a%P;return r;}int main(){ios::sync_with_stdio(0);cin.tie(0);for(int i=2;i<=N;i++){if(!v[i])p[n++]=i;for(int j=0;j<n&&i*p[j]<=N;j++){v[i*p[j]]=1;if(i%p[j]==0)break;}}int T;cin>>T>>P;M=P-1;while(T--){int a,b,c;cin>>a>>b>>c;long long r=1;for(int i=0;i<n&&p[i]<=max(a,b);i++)r=r*k(p[i],E(p[i],a,b,c))%P;cout<<"0 "<<r<<" 0\n";}}
'''
add('P5518','P5518 [MtOI2019] 幽灵乐团 _ 莫比乌斯反演基础练习题',r'''对每个质数 $q$ 单独统计原式的指数。记 $v_q(x)$ 为 $q$ 的次数，则

$$v_q\left(\frac{\operatorname{lcm}(i,j)}{\gcd(i,k)}\right)=v_q(i)+v_q(j)-\min(v_q(i),v_q(j))-\min(v_q(i),v_q(k)).$$

利用 $\sum_{i\le n}v_q(i)=\sum_{t\ge1}\lfloor n/q^t\rfloor$，可以分别求出权为 $1$ 和 $ijk$ 时的指数。第二种权值中，$q^t\mid i$ 的所有 $i$ 之和为 $q^tS(\lfloor n/q^t\rfloor)$，其中 $S(n)=n(n+1)/2$。

第三种权值使用

$$\gcd(i,j,k)=\sum_{d\mid i,j,k}\varphi(d).$$

令 $i=di',j=dj',k=dk'$，公共的 $v_q(d)$ 在上式四项中恰好抵消，因此只需枚举 $d$，把 $\varphi(d)$ 乘到缩小后的第一种指数上。全部指数对 $p-1$ 取模，最后计算各质数幂的乘积。

每次询问的枚举量约为 $\sum_d\pi(\max(A,B)/d)$，复杂度可写作 $O(n\log\log n)$，空间复杂度 $O(n)$。''',{'.cpp':A,' 数据生成.cpp':C,' 暴力.cpp':B,' 对拍.cpp':D},parts=[P0,P1],extra=[('1 998244853\n1 5 7\n','86505356 229635911 86505356\n'),('1 998244853\n2 3 4\n','6718464 311678937 6718464\n'),('1 998244853\n5 2 6\n','433707556 634255946 736585371\n'),('1 998244853\n4 5 3\n','14743630 799837924 117949040\n')])
